/*
 * AndysComputations.h
 *
 *  Created on: Aug 18, 2009
 *      Author: Andy
 */

#ifndef ANDYSCOMPUTATIONS_H_
#define ANDYSCOMPUTATIONS_H_




/*
 *  This function takes a lookup table generated by the CalibrationTest() function in calibrate.c
 *  It takes pointers to pre-allocated memory for the images fromCCD and forDLP which are
 *  unsigned character arrays in the Y800 format as employed by the Discovery 4000 DLP and the
 *  ImagingSource Camera. These are allocated with a function such as
 *
 *  fromCCD = (unsigned char *) malloc(NSIZEX * NSIZEY * sizeof(unsigned char));
 *
 *  nsizex and nsizey are ints that contain the x & y dimensionf the camera and the DLP. This will all change when we purchase a new camera
 *  with different sizes.
 *
 *  Currently ccdsizex and ccdsizey are simply placeholders, they don't do anything.
 *
 *  If DEBUG_FLAG !=0, then print debugging information.
 *
 *
 */
int ConvertCharArrayImageFromCam2DLP(int *CCD2DLPLookUp,  unsigned char* fromCCD,unsigned char* forDLP, int nsizex, int nsizey, int ccdsizex, int ccdsizey, int DEBUG_FLAG);



#endif /* ANDYSCOMPUTATIONS_H_ */
