//
// Creation:    BFTabRegister.h
// Created:     March 28, 1996
// Creator:     Bob Sheff
//
// Copyright (C) 1993-94 by BitFlow, Inc.  All Rights Reserved.
//
// BitFlow Device Register Id Definitons
//
// History:
//
// 03/28/96     rbs     Created file.
// 08/20/97     rbs     Register definitions cut out of R2Reg.h.
// 07/01/98     rbs     Modified to support all BitFlow devices.
//

#if !defined(__BFTABREGISTER__)
#define __BFTABREGISTER__


//
// Register Ids
//
// Memory object Id codes for Wide (mapped 32 bit registers), Large (mapped table 
// memory) and Narrow (bit fields within mapped 32 bit registers)
//
// Notes:
//
// 1) All wide register definitions must be declared first.
// 2) All large register definitions must be declared second.
// 3) All narrow register defintions must be declared last. 
//

typedef enum _RegId
{
	// Full 32-bit wide BitFlow device registers.
	
	REG_CON0 = 0,
	REG_CON1,
	REG_CON2,
	REG_CON3,
	REG_CON4,
	REG_CON5,
	REG_CON6,
	REG_CON7,
	REG_CON8,
	REG_CON9,
	REG_CON10,
	REG_CON11,
	REG_CON12,
	REG_CON13,
	REG_CON14,
	REG_CON15,
	REG_CON16,
	REG_CON17,
	REG_CON18,
	REG_CON19,
	REG_CON20,
	REG_CON21,
	REG_CON22,
	REG_CON23,
	REG_CON24,
	REG_CON25,
	REG_CON26,
	REG_CON27,
	REG_CON28,
	REG_CON29,
	REG_CON30,
	REG_CON31,
	REG_CON32,
	REG_CON33,
	REG_CON34,
	REG_CON35,
	REG_CON36,
	REG_CON37,
	REG_CON38,
	REG_CON39,
	REG_CON40,
	REG_CON41,
	REG_CON42,
	REG_CON43,
	REG_CON44,
	REG_CON45,
	REG_CON46,
	REG_CON47,
	REG_CON48,
	REG_CON49,
	REG_CON50,
	REG_CON51,
	REG_VFIFO,
	REG_LUTADDR,
	REG_CQ_PADDR,
	REG_CQ_LADDR,
	REG_CQ_COUNT,
	REG_CQ_DESC,
	REG_LUTDATA,
	REG_FFA,
	REG_RO_INFOHI,
	REG_RO_INFOLO,

	// Full 32-bit wide pseudo software registers.

	REG_SOFT0,

	// Full 32-bit wide UART registers for CameraLink RoadRunners and R64s.

	REG_NS_RBR,
	REG_NS_THR,
	REG_NS_DLL,
	REG_NS_IER,
	REG_NS_DLM,
	REG_NS_IIR,
	REG_NS_FCR,
	REG_NS_LCR,
	REG_NS_MCR,
	REG_NS_LSR,
	REG_NS_MSR,
	REG_NS_SCR,

	// Full 32-bit wide Raven Brooktree indirect address/data port registers (registers are actually 8 bits, but 
	// treated as 32 bit wide registers).

	REG_BT_CMND0,
	REG_BT_CMND2,
	REG_BT_CMND3,
	REG_BT_CMND4,
	REG_BT_CMND5,
	REG_BT_CMND6,
	REG_BT_CMND7,
	REG_BT_BRIGHTNESS,
	REG_BT_CONTRAST,
	REG_BT_SATURATION,
	REG_BT_HUE,
	REG_BT_HCLOCK,
	REG_BT_HDELAY,
	REG_BT_ACTIVEPIX,
	REG_BT_VDELAY,
	REG_BT_ACTIVELINES,
	REG_BT_SCFREQ,
	REG_BT_AGCDELAY,
	REG_BT_BURSTDELAY,
	REG_BT_SAMPLERATE,
	REG_BT_POLARITY,
	REG_BT_RESET,

	// Full 32-bit wide PCI 9080 local configuration registers.

	REG_P0TOL_RANGE,
	REG_P0TOL_REMAP,
	REG_MODE_ARB,
	REG_BIGEND,
	REG_PTOL_ROM_RANGE,
	REG_PTOL_ROM_REMAP,
	REG_P0TOL_BUS_DESC,
	REG_LTOP_RANGE,
	REG_LTOP_MEMORY_DECODE,
	REG_LTOP_IOCFG_DECODE,
	REG_LTOP_REMAP,
	REG_LTOP_IOCFG_CONFIG,

	REG_P1TOL_RANGE,
	REG_P1TOL_REMAP,
	REG_P1TOL_BUS_DESC,

	// Full 32-bit wide PCI 9080 shared run time registers.

	REG_MAILBOX0,
	REG_MAILBOX1,
	REG_MAILBOX2,
	REG_MAILBOX3,
	REG_MAILBOX4,
	REG_MAILBOX5,
	REG_MAILBOX6,
	REG_MAILBOX7,
	REG_PTOL_DOORBELL,
	REG_LTOP_DOORBELL,
	REG_INT_CON_STAT,
	REG_PCI_COM_PROM_CON,

	REG_PCI_PLX_CFG_ID,
	REG_PCI_PLX_REV,

	// Full 32-bit wide PCI 9080 global configuration registers.

	REG_CFG_ID,
	REG_CFG_COM_STAT,
	REG_CFG_REV_CLASS,
	REG_CFG_SETUP,
	REG_CFG_BAR0,
	REG_CFG_BAR1,
	REG_CFG_BAR2,
	REG_CFG_BAR3,
	REG_CFG_BAR4,
	REG_CFG_BAR5,
	REG_CFG_CARDBUS,
	REG_CFG_SUBVEN_SUBSYS,
	REG_CFG_ROM_BASE,
	REG_CFG_INT_BURST,

	// Full 32-bit wide PCI 9080 local DMA registers.

	REG_DMA_CH0_MODE,
	REG_DMA_CH0_PADDR,
	REG_DMA_CH0_LADDR,
	REG_DMA_CH0_COUNT,
	REG_DMA_CH0_DESC,
	REG_DMA_CH1_MODE,
	REG_DMA_CH1_PADDR,
	REG_DMA_CH1_LADDR,
	REG_DMA_CH1_COUNT,
	REG_DMA_CH1_DESC,
	REG_DMA_COM_STAT,
	REG_DMA_ARB0,
	REG_DMA_ARB1,

	// Full 32-bit wide QuickLogic QL5064 registers.

	REG_00_WRITE0_ADDR_LO,
	REG_04_WRITE0_ADDR_HI,
	REG_08_WRITE0_COUNT_REQ,
	REG_0C_WRITE0_COUNT_REM,
	REG_10_WRITE1_ADDR_LO,
	REG_14_WRITE1_ADDR_HI,
	REG_18_WRITE1_COUNT_REQ,
	REG_1C_WRITE1_COUNT_REM,
	REG_20_PCI_STATUS,
	REG_24_PCI_STATUS,
	REG_28_PCI_STATUS,
	REG_2C_PCI_STATUS,
	REG_30_I2O_INT_REQ,
	REG_34_I2O_INT_MASK,
	REG_40_I2O_QUEUE_IN,
	REG_44_I2O_QUEUE_OUT,
	REG_48_READ0_ADDR_LO,
	REG_4C_READ0_ADDR_HI,
	REG_50_READ0_COUNT_REQ,
	REG_54_READ0_COUNT_REM,
	REG_58_READ1_ADDR_LO,
	REG_5C_READ1_ADDR_HI,
	REG_60_READ1_COUNT_REQ,
	REG_64_READ1_COUNT_REM,
	REG_68_RCV_FIFO_STATUS,
	REG_6C_XMT_FIFO_STATUS,
	REG_70_MAIL_OUT,
	REG_74_MAIL_OUT,
	REG_78_MAIL_IN,
	REG_7C_MAIL_IN,
	REG_84_INT_AND_MAIL_STATUS,
	REG_88_INT_ENABLES,
	REG_8C_INT_ENABLES,
	REG_90_DMA_MAIL_I2O_STATUS,
	REG_94_ERROR_STATUS,
	REG_D0_DMA_CONTROL,
	REG_D4_DMA_CONTROL,
	REG_E8_RESET_TOTAL,
	REG_EC_RESET_FPGA,

	// Full 32-bit wide Alta-AN AFE indirect address/data port registers 

	REG_AFE_DEVID,				
	REG_AFE_SYNC_STAT,			
	REG_AFE_SYNC_POL,			
	REG_AFE_HSYNC_SLICER,		
	REG_AFE_SOG_SLICER,			
	REG_AFE_IN_CNF,				
	REG_AFE_RED_GAIN,			
	REG_AFE_GREEN_GAIN,			
	REG_AFE_BLUE_GAIN,			
	REG_AFE_RED_OFFS,			
	REG_AFE_GREEN_OFFS,			
	REG_AFE_BLUE_OFFS,			
	REG_AFE_OFFS_DAC_CNF,		
	REG_AFE_BANDWIDTH,			
	REG_AFE_PLL_HTOTAL_MSB,		
	REG_AFE_PLL_HTOTAL_LSB,		
	REG_AFE_PLL_SAMPLE_PHASE,	
	REG_AFE_PLL_PRE_COAST,		
	REG_AFE_PLL_POST_COAST,		
	REG_AFE_PLL_MISC,			
	REG_AFE_DC_RSTR_PIX_MSB,	
	REG_AFE_DC_RSTR_PIX_LSB,	
	REG_AFE_DC_RSTR_WIDTH,		
	REG_AFE_ABLC_CNF,			
	REG_AFE_OUT_FORMAT,			
	REG_AFE_HSOUT_WIDTH,		
	REG_AFE_OUT_SIG_DISABLE,	
	REG_AFE_POWER_CON,			
	REG_AFE_PLL_TUNING,			
	REG_AFE_RED_ABLC,			
	REG_AFE_GREEN_ABLC,			
	REG_AFE_BLUE_ABLC,			
	REG_AFE_DC_RSTR_CLAMP,		
	REG_AFE_SYNC_SEP_CON,		

	// Full 32-bit wide Alta-CO AFE indirect address/data port registers 

	REG_CFE_INPUT_CTRL_00,
	REG_CFE_VIDEO_SELECTION_01,
	REG_CFE_RESERVED_02,
	REG_CFE_OUTPUT_CTRL_03,
	REG_CFE_EXTENDED_OUTPUT_CTRL_04,
	REG_CFE_RESERVED_05,
	REG_CFE_RESERVED_06,
	REG_CFE_AUTODETECT_ENABLE_07,
	REG_CFE_CONTRAST_08,
	REG_CFE_RESERVED_09,
	REG_CFE_BRIGHTNESS_0A,
	REG_CFE_HUE_0B,
	REG_CFE_DEFAULT_VALUE_Y_0C,
	REG_CFE_DEFAULT_VALUE_C_0D,
	REG_CFE_ADI_CTRL_0E,
	REG_CFE_POWER_MANAGEMENT_0F,
	REG_CFE_STATUS_1_10,
	REG_CFE_IDENT_11,
	REG_CFE_STATUS_2_12,
	REG_CFE_STATUS_3_13,
	REG_CFE_ANALOG_CLAMP_CTRL_14,
	REG_CFE_DIGITAL_CLAMP_CTRL_1_15,
	REG_CFE_RESERVED_16,
	REG_CFE_SHAPING_FILTER_CTRL_17,
	REG_CFE_SHAPING_FILTER_CTRL_2_18,	
	REG_CFE_COMB_FILTER_CTRL_19,
	REG_CFE_RESERVED_1A,
	REG_CFE_RESERVED_1B,
	REG_CFE_RESERVED_1C,
	REG_CFE_ADI_CTRL_2_1D,
	REG_CFE_RESERVED_1E,
	REG_CFE_RESERVED_1F,
	REG_CFE_RESERVED_20,
	REG_CFE_RESERVED_21,
	REG_CFE_RESERVED_22,
	REG_CFE_RESERVED_23,
	REG_CFE_RESERVED_24,
	REG_CFE_RESERVED_25,
	REG_CFE_RESERVED_26,
	REG_CFE_PIXEL_DELAY_CTRL_27,
	REG_CFE_RESERVED_28,
	REG_CFE_RESERVED_29,
	REG_CFE_RESERVED_2A,
	REG_CFE_MISC_GAIN_CTRL_2B,
	REG_CFE_AGC_MODE_CTRL_2C,
	REG_CFE_CHROMA_GAIN_CTRL_1_2D,
	REG_CFE_CHROMA_GAIN_CTRL_2_2E,
	REG_CFE_LUMA_GAIN_CTRL_1_2F,
	REG_CFE_LUMA_GAIN_CTRL_2_30,
	REG_CFE_VSYNC_FIELD_CTRL_1_31,
	REG_CFE_VSYNC_FIELD_CTRL_2_32,
	REG_CFE_VSYNC_FIELD_CTRL_3_33,
	REG_CFE_HSYNC_POSITION_CTRL_1_34,
	REG_CFE_HSYNC_POSITION_CTRL_2_35,
	REG_CFE_HSYNC_POSITION_CTRL_3_36,
	REG_CFE_POLARITY_37,
	REG_CFE_NTSC_COMB_CTRL_38,
	REG_CFE_PAL_COMB_CTRL_39,
	REG_CFE_ADC_CTRL_3A,
	REG_CFE_RESERVED_3B,
	REG_CFE_RESERVED_3C,
	REG_CFE_MANUAL_WINDOW_CTRL_3D,
	REG_CFE_RESERVED_3E,
	REG_CFE_RESERVED_3F,
	REG_CFE_RESERVED_40,
	REG_CFE_RESAMPLE_CTRL_41,
	REG_CFE_RESERVED_42,
	REG_CFE_RESERVED_43,
	REG_CFE_RESERVED_44,
	REG_CFE_RESERVED_45,
	REG_CFE_RESERVED_46,
	REG_CFE_RESERVED_47,
	REG_CFE_GEMSTAR_CTRL_1_48,
	REG_CFE_GEMSTAR_CTRL_2_49,
	REG_CFE_GEMSTAR_CTRL_3_4A,
	REG_CFE_GEMSTAR_CTRL_4_4B,
	REG_CFE_GEMSTAR_CTRL_5_4C,
	REG_CFE_CTI_DNR_CTRL_1_4D,
	REG_CFE_CTI_DNR_CTRL_2_4E,
	REG_CFE_RESERVED_4F,
	REG_CFE_CTI_DNR_CTRL_4_50,
	REG_CFE_LOCK_COUNT_51,
	REG_CFE_RESERVED_52,
	REG_CFE_RESERVED_53,
	REG_CFE_RESERVED_54,
	REG_CFE_RESERVED_55,
	REG_CFE_RESERVED_56,
	REG_CFE_RESERVED_57,
	REG_CFE_RESERVED_58,
	REG_CFE_RESERVED_59,
	REG_CFE_RESERVED_5A,
	REG_CFE_RESERVED_5B,
	REG_CFE_RESERVED_5C,
	REG_CFE_RESERVED_5D,
	REG_CFE_RESERVED_5E,
	REG_CFE_RESERVED_5F,
	REG_CFE_RESERVED_60,
	REG_CFE_RESERVED_61,
	REG_CFE_RESERVED_62,
	REG_CFE_RESERVED_63,
	REG_CFE_RESERVED_64,
	REG_CFE_RESERVED_65,
	REG_CFE_RESERVED_66,
	REG_CFE_RESERVED_67,
	REG_CFE_RESERVED_68,
	REG_CFE_RESERVED_69,
	REG_CFE_RESERVED_6A,
	REG_CFE_RESERVED_6B,
	REG_CFE_RESERVED_6C,
	REG_CFE_RESERVED_6D,
	REG_CFE_RESERVED_6E,
	REG_CFE_RESERVED_6F,
	REG_CFE_RESERVED_70,
	REG_CFE_RESERVED_71,
	REG_CFE_RESERVED_72,
	REG_CFE_RESERVED_73,
	REG_CFE_RESERVED_74,
	REG_CFE_RESERVED_75,
	REG_CFE_RESERVED_76,
	REG_CFE_RESERVED_77,
	REG_CFE_RESERVED_78,
	REG_CFE_RESERVED_79,
	REG_CFE_RESERVED_7A,
	REG_CFE_RESERVED_7B,
	REG_CFE_RESERVED_7C,
	REG_CFE_RESERVED_7D,
	REG_CFE_RESERVED_7E,
	REG_CFE_RESERVED_7F,
	REG_CFE_RESERVED_80,
	REG_CFE_RESERVED_81,
	REG_CFE_RESERVED_82,
	REG_CFE_RESERVED_83,
	REG_CFE_RESERVED_84,
	REG_CFE_RESERVED_85,
	REG_CFE_RESERVED_86,
	REG_CFE_RESERVED_87,
	REG_CFE_RESERVED_88,
	REG_CFE_RESERVED_89,
	REG_CFE_RESERVED_8A,
	REG_CFE_RESERVED_8B,
	REG_CFE_RESERVED_8C,
	REG_CFE_RESERVED_8D,
	REG_CFE_RESERVED_8E,
	REG_CFE_FREE_RUN_LINE_LENGTH_1_8F,
	REG_CFE_VBI_INFO_90,
	REG_CFE_WSS_1_91,
	REG_CFE_WSS_2_92,
	REG_CFE_EDTV_1_93,
	REG_CFE_EDTV_2_94,
	REG_CFE_EDTV_3_95,
	REG_CFE_CGMS_1_96,
	REG_CFE_CGMS_2_97,
	REG_CFE_CGMS_3_98,
	REG_CFE_CCAP_1_99,
	REG_CFE_CCAP_2_9A,
	REG_CFE_LETTERBOX_1_9B,
	REG_CFE_LETTERBOX_2_9C,
	REG_CFE_LETTERBOX_3_9D,
	REG_CFE_RESERVED_9E,
	REG_CFE_RESERVED_9F,
	REG_CFE_RESERVED_A0,
	REG_CFE_RESERVED_A1,
	REG_CFE_RESERVED_A2,
	REG_CFE_RESERVED_A3,
	REG_CFE_RESERVED_A4,
	REG_CFE_RESERVED_A5,
	REG_CFE_RESERVED_A6,
	REG_CFE_RESERVED_A7,
	REG_CFE_RESERVED_A8,
	REG_CFE_RESERVED_A9,
	REG_CFE_RESERVED_AA,
	REG_CFE_RESERVED_AB,
	REG_CFE_RESERVED_AC,
	REG_CFE_RESERVED_AD,
	REG_CFE_RESERVED_AE,
	REG_CFE_RESERVED_AF,
	REG_CFE_RESERVED_B0,
	REG_CFE_RESERVED_B1,
	REG_CFE_CRC_ENABLE_B2,
	REG_CFE_RESERVED_B3,
	REG_CFE_RESERVED_B4,
	REG_CFE_RESERVED_B5,
	REG_CFE_RESERVED_B6,
	REG_CFE_RESERVED_B7,
	REG_CFE_RESERVED_B8,
	REG_CFE_RESERVED_B9,
	REG_CFE_RESERVED_BA,
	REG_CFE_RESERVED_BB,
	REG_CFE_RESERVED_BC,
	REG_CFE_RESERVED_BD,
	REG_CFE_RESERVED_BE,
	REG_CFE_RESERVED_BF,
	REG_CFE_RESERVED_C0,
	REG_CFE_RESERVED_C1,
	REG_CFE_RESERVED_C2,
	REG_CFE_ADC_SWITCH_1_C3,
	REG_CFE_ADC_SWITCH_2_C4,
	REG_CFE_RESERVED_C5,
	REG_CFE_RESERVED_C6,
	REG_CFE_RESERVED_C7,
	REG_CFE_RESERVED_C8,
	REG_CFE_RESERVED_C9,
	REG_CFE_RESERVED_CA,
	REG_CFE_RESERVED_CB,
	REG_CFE_RESERVED_CC,
	REG_CFE_RESERVED_CD,
	REG_CFE_RESERVED_CE,
	REG_CFE_RESERVED_CF,
	REG_CFE_RESERVED_D0,
	REG_CFE_RESERVED_D1,
	REG_CFE_RESERVED_D2,
	REG_CFE_RESERVED_D3,
	REG_CFE_RESERVED_D4,
	REG_CFE_RESERVED_D5,
	REG_CFE_RESERVED_D6,
	REG_CFE_RESERVED_D7,
	REG_CFE_RESERVED_D8,
	REG_CFE_RESERVED_D9,
	REG_CFE_RESERVED_DA,
	REG_CFE_RESERVED_DB,
	REG_CFE_LETTERBOX_CTRL_1_DC,
	REG_CFE_LETTERBOX_CTRL_2_DD,
	REG_CFE_RESERVED_DE,
	REG_CFE_RESERVED_DF,
	REG_CFE_RESERVED_E0,
	REG_CFE_SD_OFFSET_CB_E1,
	REG_CFE_SD_OFFSET_CR_E2,
	REG_CFE_SD_SATURATION_CB_E3,
	REG_CFE_SD_SATURATION_CR_E4,
	REG_CFE_NTSC_V_BIT_BEGIN_E5,
	REG_CFE_NTSC_V_BIT_END_E6,
	REG_CFE_NTSC_F_BIT_TOGGLE_E7,
	REG_CFE_PAL_V_BIT_BEGIN_E8,
	REG_CFE_PAL_V_BIT_END_E9,
	REG_CFE_PAL_F_BIT_TOGGLE_EA,
	REG_CFE_RESERVED_EB,
	REG_CFE_RESERVED_EC,
	REG_CFE_RESERVED_ED,
	REG_CFE_RESERVED_EE,
	REG_CFE_RESERVED_EF,
	REG_CFE_RESERVED_F0,
	REG_CFE_RESERVED_F1,
	REG_CFE_RESERVED_F2,
	REG_CFE_RESERVED_F3,
	REG_CFE_DRIVE_STRENGTH_F4,
	REG_CFE_RESERVED_F5,
	REG_CFE_RESERVED_F6,
	REG_CFE_RESERVED_F7,
	REG_CFE_IF_COMP_CTRL_F8,
	REG_CFE_VS_MODE_CTRL_F9,

	// Large non-register memory objects.

	REG_CTAB,
	REG_QTAB,
	REG_DPM,

    #define BFObjectCount (REG_DPM + 1)		// Number of Wide and Large memory objects.

    // Narrow memory objects (bit fields within registers).

    // Shared bit field registers.

    REG_AEFA,
    REG_AEFB,
    REG_AEFC,
    REG_AEFD,
    REG_EFA,
    REG_EFB,
    REG_EFC,
    REG_EFD,
    REG_LTEOX,
    REG_LTMBANK,
    REG_LTMBYPASS,
    REG_LTMCHSEL,
    REG_LTFLUSH,
    REG_SW,
    REG_OVF,
    REG_LTAACTIVE,
    REG_LTBACTIVE,
    REG_LTCACTIVE,
    REG_LTDACTIVE,
    REG_NORLUTS,
    REG_ADVANCE,
    REG_FRZFIFO,
    REG_GRNTCTL,
    REG_INT_DMA,
	REG_QTBSRC,
    REG_AACTIVE,
    REG_BACTIVE,
    REG_CACTIVE,
    REG_DACTIVE,
    REG_CMDWRITE,
	REG_SWTRIGA,
	REG_SWTRIGB,
    REG_HBANK,
    REG_HBYPASS,
    REG_SCHSEL,
    REG_MUXA,
    REG_MUXB,
    REG_MUXC,
    REG_MUXD,
    REG_LENPOL,
    REG_FENPOL,
    REG_GPOUT0,
    REG_GPOUT1,
    REG_GPOUT2,
    REG_GPOUT3,
    REG_GPOUT4,
    REG_GPOUT5,
    REG_ENCPOL,
    REG_VCOUNT,
    REG_CFGDATA,
    REG_CFGCLOCK,
	REG_CFREQ,
    REG_AQSTAT,
    REG_FI,
    REG_FIRSTFI,
    REG_FACTIVE,
	REG_FCOUNT,
    REG_TRIGPOL,
    REG_PROT,
    REG_CTABHOLD,
    REG_HSTOP,
	REG_VSTOP,
	REG_ENHLOAD,
	REG_VTRIGRST,
	REG_FISEL,
    REG_ENCLAMP,
	REG_AQSRC,
    REG_GPIN1,
    REG_GPIN2,
	REG_LBCREV,
	REG_SWRESET,

	// UART bit field registers for CameraLink RoadRunners and R64s.

	REG_NS_DATA_IN,

	REG_NS_DATA_OUT,

	REG_NS_BAUD_DIV_LO,

	REG_NS_EINT_RECEIVE,
	REG_NS_EINT_TRANSMIT,
	REG_NS_EINT_LINE,
	REG_NS_EINT_MODEM,

	REG_NS_BAUD_DIV_HI,

	REG_NS_NO_INTS,
	REG_NS_HIGH_INT,
	REG_NS_TIMEOUT,
	REG_NS_FIFOS_ACTIVE,

	REG_NS_FIFO_ENABLE,
	REG_NS_CLEAR_RECEIVE,
	REG_NS_CLEAR_TRANSMIT,
	REG_NS_DMA_MULTIPLE,
	REG_NS_TRIG_LEV,

	REG_NS_BITS,
	REG_NS_STOPS,
	REG_NS_PARITY_ENABLE,
	REG_NS_PARITY_EVEN,
	REG_NS_PARITY_STICK,
	REG_NS_BREAK,
	REG_NS_BAUD_DIV_ACCESS,

	REG_NS_DTR,
	REG_NS_RTS,
	REG_NS_OUT1,
	REG_NS_OUT2,
	REG_NS_LOOP,

	REG_NS_DR,
	REG_NS_OE,
	REG_NS_PE,
	REG_NS_FE,
	REG_NS_BI,
	REG_NS_THRE,
	REG_NS_TEMT,
	REG_NS_FIFO,

	REG_NS_DCTS,
	REG_NS_DDSR,
	REG_NS_TERI,
	REG_NS_DDCD,
	REG_NS_CTS,
	REG_NS_DSR,
	REG_NS_RI,
	REG_NS_DCD,

	REG_NS_SCRATCH,

	// Unique bit field registers for RoadRunner CON0.

	REG_SYNCSEL,
	REG_PROGFIFO,
	REG_CLKCON,

    // Unique bit field registers for RoadRunner CON1.

	REG_AQCMD,
	REG_TOPA,
	REG_TOPB,
	REG_TOPC,
	REG_TOPD,
	REG_FI_CON,

	REG_PLXGAREV,
	REG_FULL_A,
	REG_HFA,
	REG_FULL_B,

    // Unique bit field registers for RoadRunner CON2.

	REG_ENGPOUT0,
	REG_ENGPOUT1,
	REG_ENGPOUT2,
	REG_ENCT0,
	REG_ENCT1,
	REG_ENCT2,
	REG_BURST,
    REG_ONEQTB,
    REG_INT0_CTAB,
	REG_INT1_FIFO,
	REG_INT2_HW,
	REG_LTMBY8,
	REG_TRIGINT,
	REG_TRIGSTAT,

	REG_INT3_TRIG,
	REG_INT4_SER,
	REG_CONTRIGINT,

    // Unique bit field registers for RoadRunner CON3.

	REG_CLKDRVSEL,
	REG_TPSEL0,
	REG_TPSEL1,
	REG_TRIGINTB,	
	REG_TRIGSTATB,	
	REG_TRIGLT,		
	REG_TRIGLTB,	


    // Unique bit field registers for RoadRunner CON4.

	REG_ENINT0_CTAB,
	REG_ENINT1_FIFO,
	REG_ENINT2_HW,
	REG_SYNCMSTR,
	REG_SYNCBUSY,
	REG_LTQBANK,
	REG_CONTINTPOL,
	REG_TRIG_FILTER,
	REG_FORCEABORT,
	REG_AQFLD,
	REG_DBANK,
	REG_AQFRM,
	REG_VFRESET,
	REG_TRIGAQCMD,
	REG_HBY8,

	REG_ENINT3_TRIG,
	REG_ENINT4_SER,
	REG_VF_MRST,
	REG_SEN,
	REG_FWSI,
	REG_LD_FIFO,
	REG_RST_SER,

    // Unique bit field registers for RoadRunner CON5.

	REG_TRIGCON,
	REG_ENCDRCON,
	REG_CT0CON,
	REG_CT1CON,
	REG_CT2CON,
	REG_ENXTRIG,

    // Unique bit field registers for RoadRunner CON6.

	REG_STRAIGHT,
	REG_DTG,
	REG_TRIM,
	REG_TG1AQW,
	REG_TG2AQW,
	REG_TGA,
	REG_TGB,
	REG_TGC,
	REG_TGD,
	REG_HSTICK,
	REG_DLY,

	REG_TGAQW,
	REG_RD_TRIGA,
	REG_RD_TRIGB,
	REG_RD_ENCA,
	REG_RD_ENCB,
	REG_RANDOM_FEN,
	REG_BY16,

    // Unique bit field registers for RoadRunner CON7.
	
	REG_FM_LEVEL,
	REG_FM_MAX,
	REG_H_ERR,
	REG_FM_RESET,
    REG_ROTINV,

    // Unique bit field registers for RoadRunner CON8.

	REG_ENC_FILTER,
	REG_LAL,
	REG_TRIG_FREE,
	REG_HCTAB_X16,
	REG_FENHRESET,
	REG_STCON,
	REG_VSTICK,
	REG_FEN_SIZE,

	REG_CTABREV,
	REG_FEN_IS_TRIG,

    // Unique bit field registers for RoadRunner CON9.

	REG_TRIG_DELAY,
	REG_EN_TRIG_DELAY,
	REG_TRIMP4,

    // Unique bit field registers for RoadRunner CON10.

    REG_TRIGASTOP,
	REG_LEN_SIZE,

	REG_CC1_CON,
	REG_CC2_CON,
	REG_CC3_CON,
	REG_CC4_CON,
	REG_HTRIM,
 
	// Unique bit field registers for RoadRunner CON11.

	REG_CFGSTATUS,
	REG_CFGEN,
	REG_CFGDONE,
	REG_OCCONFIG,

	// Unique bit field registers for Road Runner CL CON0

	REG_XTL_7MHZ,

    // Unique bit field registers for Raven CON0.

    REG_AQCMDJ,
    REG_AQSTATJ,
    REG_AQCMDK,
    REG_AQSTATK,
    REG_FIJ,
    REG_FIRSTFIJ,
    REG_FACTIVEJ,
    REG_FCOUNTJ,
    REG_FIK,
    REG_FIRSTFIK,
    REG_FACTIVEK,
    REG_FCOUNTK,
    REG_SYNTLEVEL,
	REG_ENGEN,
	REG_MANDMA,
	REG_SWCON,

    // Unique bit field registers for Raven CON1.

    REG_LENGINEK,
    REG_CAMSEL,
    REG_EOT,
    REG_GPIN3,
    REG_ENLPF,

    // Unique bit field registers for Raven CON2.

    REG_J_DONE,
	REG_J_DONE_RST,
    REG_K_DONE,
	REG_K_DONE_RST,
    REG_AQFLDJ,
    REG_AQFRMJ,
    REG_AQFLDK,
    REG_AQFRMK,
    REG_INTJENDVB,
    REG_INTKENDVB,
    REG_INT_CCUJ,
    REG_INT_FIFO,
    REG_INT_HW,
    REG_INT_CCUK,

    // Unique bit field registers for Raven CON3.

    REG_ENINT_CCUJ,
    REG_ENINT_FIFO,
    REG_ENINT_HW,
    REG_ENINT_CCUK,
    REG_RSTPLX,
	REG_RESETJ,
    REG_ICSFREQ,
	REG_ENXTRIGA,
	REG_ENXTRIGB,
	REG_RESETFF,
	REG_RESETK,
	REG_CLRDMA,
	REG_TRIGPOLA,
	REG_TRIGPOLB,
	REG_TWO_IN_ONE_DMA,

    // Unique bit field registers for Raven CON4.

    REG_VIDEO_ON,
    REG_SYNTVID,
	REG_ABORTDMA,
	REG_QJMOD,
	REG_QJBANK,
	REG_LTQJBANK,
	REG_QKMOD,
	REG_QKBANK,
	REG_LTQKBANK,

    // Unique bit field registers for Raven CON6.

    REG_DIGTESTPAT,
	REG_DIG202,
	REG_DIG213,
	REG_SMLMUXREV,
	REG_MUXREV,

    // Unique bit field registers for Raven CON7.

    REG_SELPCLKIN0,
    REG_POLCLKIN,
    REG_SELPCLKIN1,

    // Unique bit field registers for Raven CON8.

    REG_SELPCLKIN2,
    REG_SELPCLKIN3,
	REG_PLLREV,

    // Unique bit field registers for Raven CON9.

    REG_FREQSEL,
	REG_DISBLOSC,
    REG_2XPCLK,
    REG_EN125MHZ,
    REG_RGBCLK,
    REG_CLKINSEL,

    // Unique bit field registers for Raven CON10.

    REG_SYNCDIR02,
    REG_SYNCDIR13,
    REG_VID2DET02,
    REG_VID2DET13,
	REG_SYNCTERM01,
	REG_AC_CLKIN,
    REG_CTCON,
	REG_TRIGMOD,
	REG_HPERIOD,

    // Unique bit field registers for Raven CON11.

    REG_SYNCSEL0,
    REG_SYNCSEL1,
    REG_SYNCSEL2,
    REG_SYNCSEL3,
	REG_HLOW,

	// Unique bit field registers for Raven CON12.

	REG_DIVENCL,
	REG_VPERIOD,

    // Unique bit field registers for Raven CON13.

    REG_HONESHOT,
	REG_DUALTAP01,
	REG_DUALTAP23,
	REG_DIVENCH,
	REG_ENCPHASE,
	REG_VLOW,

    // Unique bit field registers for Raven CON14.

    REG_ABPP,
    REG_CCUREV,

    // Unique bit field registers for Raven CON15.

    REG_STROBCON,
    REG_SLVENC0,

    // Unique bit field registers for Raven CON16.

    REG_SELVCOUNT,
    REG_GPIN0,

    // Unique bit field registers for Raven CON17.

    // Unique bit field registers for Raven CON18.

    REG_CFGEN6K10K,
    REG_CFGEN8K,
    REG_CFGDONELBC,

    // Unique bit field registers for Raven CON19.

	REG_CFGENDONE,
    REG_CFGDONEPLL,
    REG_CFGDONECCU,
    REG_CFGDONEMUX,

    // Unique bit field registers for Raven CON20.

    REG_BT_ADDRESS,

    // Unique bit field registers for Raven CON21.

    REG_BT_RSV0,

    // Unique bit field registers for Raven CON22.

    REG_BT_CONTROL,

    // Unique bit field registers for Raven CON23.

    REG_BT_RSV1,

    // Unique bit field registers for Raven CON24.

    REG_GAIN2,

    // Unique bit field registers for Raven CON25.

    REG_OFFSET2,

    // Unique bit field registers for Raven CON26.

    REG_GAIN3,

    // Unique bit field registers for Raven CON27.

    REG_OFFSET3,

    // Unique bit field registers for Raven CON28.

    REG_GAIN0,

    // Unique bit field registers for Raven CON29.

    REG_OFFSET0,

    // Unique bit field registers for Raven CON30.

    REG_GAIN1,
	REG_FIPOL,
	REG_SELFI,

    // Unique bit field registers for Raven CON31.

    REG_OFFSET1,

    // Unique bit field registers for Raven CON32.

    REG_HSTART,

    // Unique bit field registers for Raven CON33.

    REG_HSIZE,

    // Unique bit field registers for Raven CON34.

    REG_VSIZE,

    // Unique bit field registers for Raven CON35.

	REG_CLAMP,

    // Unique bit field registers for Raven CON36.

    REG_VSTART0,

    // Unique bit field registers for Raven CON37.

    REG_VSTART3,
	REG_VSTARTP,

    // Unique bit field registers for Raven CON38.

    REG_STROBE0,
    REG_STROBEPOL,

    // Unique bit field registers for Raven CON39.

    REG_STROBE3,
    REG_STROBEP,

    // Unique bit field registers for Raven CON40.

    REG_STARTCTA0,
    REG_CTAPOL,

    // Unique bit field registers for Raven CON41.

    REG_STARTCTA3,
	REG_CTAP,

    // Unique bit field registers for Raven CON42.

    REG_CTASIZE0,
    
     // Unique bit field registers for Raven CON44.

    REG_STARTCTB0,
    REG_CTBPOL,

    // Unique bit field registers for Raven CON45.

    REG_STARTCTB3,
    REG_CTBP,

    // Unique bit field registers for Raven CON46.

    REG_SRAM_ADDRESS,
    REG_SRAM_SELECTA,
    REG_SRAM_BYTE0,
    REG_SRAM_BYTE1,
    REG_SRAM_BYTE2,
    REG_SRAM_BYTE3,

    // Unique bit field registers for Raven CON47.

    REG_SRAM_PORT,

	// Unique bit field registers for Raven Quad Controller.

	REG_CQ_TSIZE,

	REG_CQ_CHAN_LOW,
	REG_CQ_EOX_LOW,
	REG_CQ_BANK_LOW,
	REG_CQ_BYPASS_LOW,
	REG_CQ_MCHSEL_LOW,
	REG_CQ_FLUSH_LOW,
	REG_CQ_ADDR,
	REG_CQ_CHAN_HI,
	REG_CQ_EOX_HI,
	REG_CQ_BANK_HI,
	REG_CQ_BYPASS_HI,
	REG_CQ_MCHSEL_HI,
	REG_CQ_FLUSH_HI,

	REG_CQ_DESC_PCI_SPACE,
	REG_CQ_DESC_CHAIN_END,
	REG_CQ_DESC_COUNT_INT,
	REG_CQ_DESC_TRAN_LTOP,
	REG_CQ_DESC_NEXT,

	// Unique bit field registers for Raven FFA.

	REG_FFA_ODD_J,
	REG_FFA_ODD_K,

	// Unique bit field registers for R64 CON0.

	REG_FW_7MHZ,
	REG_L_CLKCON,
	REG_SEL_UCLK_7MHZ,
	REG_RELOAD_FPGA,
	REG_FW_SEL,
	REG_CPLD_MODE,

	// Unique bit field registers for R64 CON1.

	REG_VCNT_RLS_ZERO,
	REG_VCNT_RST,
	REG_VCNT_LD,
	REG_VCNT_RLS_STK,
	REG_ABORT_CON,
	REG_NO_VB_WAIT,
	REG_ACQ_CON,
	REG_FREEZE_CON,
	REG_ACQ_SAFETY,
	REG_NO_RULE,
	REG_INT_CTAB,
	REG_INT_OVSTEP,
	REG_INT_TRIG,
	REG_INT_SER,
	REG_INT_QUAD,
	REG_INT_TRIGCON,

	// Unique bit field registers for R64 CON2.

	REG_HCNT_RLS_ZERO,
	REG_HCNT_RST,
	REG_HCNT_LD,
	REG_HCNT_RLS_STK,
	REG_RST_HVCOUNT,
	REG_RST_DPM_ADDR,
	REG_CTAB_RLE,

	// Unique bit field registers for R64 CON3.

	REG_REV_DCC,
	REG_AUX_DETECT,
	REG_GPIN4,

	// Unique bit field registers for R64 CON4.

	REG_ENINT_CTAB,
	REG_ENINT_OVSTEP,
	REG_ENINT_TRIG,
	REG_ENINT_SER,
	REG_ENINT_QUAD,
	REG_EOF_IN_AQ,
	REG_INT_ANY,
	REG_ENINT_ALL,
	REG_AUX_CAM,
	REG_GPOUT6,
	REG_OVS,
	REG_RST_OVS,
	REG_CL_DISABLE,
	REG_LCOUNT,
	REG_PCOUNT,
	REG_FENCOUNT,
	REG_POP_TOSS,
	REG_PUMP_OFF,
	REG_DMA_BUSY,
	REG_HAW_START,
	REG_VAW_START,

	// Unique bit field registers for R64 CON5.

	REG_SEL_TRIG,
	REG_SW_TRIG,
	REG_SELENC,
	REG_SW_ENC,
	REG_RD_TRIG_DIFF,
	REG_RD_TRIG_TTL,
	REG_RD_TRIG_OPTO,
	REG_RD_ENC_DIFF,
	REG_RD_ENC_TTL,
	REG_RD_ENC_OPTO,
	REG_TRIGGER_DELAY,
	REG_ENINT_EOF,
	REG_INT_EOF,
	REG_RD_FEN,
	REG_EN_TRIGGER,
	REG_EN_ENCODER,

	// Unique bit field registers for R64 CON6.

	REG_ENC_DIV,
	REG_ENC_DIV_M,
	REG_HCOUNT,
	REG_TRIG_QUALIFIED,

	// Unique bit field registers for R64 CON7.

	REG_AQ_COUNT,
	REG_SEL_REG_GEN,
	REG_GEN_ONESHOT,
	REG_TAG_BANK,
	REG_NTG_TO_ENC,
	REG_NTG_TO_TRIG,

	// Unique bit field registers for R64 CON8.

	REG_GPOUT0_CON,
	REG_GPOUT1_CON,
	REG_GPOUT2_CON,
	REG_GPOUT3_CON,
	REG_GPOUT4_CON,
	REG_GPOUT5_CON,
	REG_GPOUT6_CON,
	REG_AFPDF,
	REG_RLE_LOAD_H,
	REG_RLE_LOAD_V,

	// Unique bit field registers for R64 CON9.

	REG_MUX_REV,
	REG_FW_TYPE,
	REG_DISPLAY,
	REG_CLIP,
	REG_SHORT_FRAME,
	REG_RST_CALC_BANK,
	REG_CALC_BANK,
	REG_ACPL_MUL,

	// Unique bit field registers for R64 CON10.

	REG_FORMAT,
	REG_VID_SOURCE,
	REG_ACPL,
	REG_PIX_DEPTH,
	REG_FORCE_8BIT,

	// Unique bit field registers for R64 CON11.

	REG_ALAST_ADD,
	REG_DPM_WP,
	REG_BLAST_ADD,
	REG_UART_MASTER,

	// Unique bit field registers for R64 CON12.

	REG_CLAST_ADD,
	REG_DLAST_ADD,
	REG_RGBHSI,

	// Unique bit field registers for R64 CON13.

	REG_VIDEO_MASK,

	// Unique bit field registers for R64 CON14.

	REG_BUTTONS,
	REG_SHIFT_RAW,
	REG_SHIFT_RAW_LEFT,
	REG_DELAY,
	REG_SWAP,
	REG_UART_CON,
	REG_DPM_SPLIT,

	// Unique bit field registers for R64 CON15.

	REG_SOURCE_ADD,
	REG_TAG_QUAD,
	REG_QUAD_INFO,
	REG_QENC_INTRVL_LL,		
	REG_QENC_DECODE,		
	REG_QENC_AQ_DIR,			
	REG_QENC_INTRVL_MODE,	
	REG_QENC_NO_REAQ,		
	REG_QENC_DUAL_PHASE,	
	REG_SCAN_STEP_TRIG,
	REG_QENC_RESET,			

	// Unique bit field registers for R64 CON16.

	REG_TXC,
	REG_QUAD_INT,
	REG_TAIL_TAG,
	REG_HEAD_TAG,
	REG_TXC_INFO,
	REG_EOC,
	REG_QENC_INTRVL_UL,		
	REG_QENC_RESET_MODE,
	REG_ENC_DIV_FORCE_DC,
	REG_ENC_DIV_OPEN_LOOP,
	REG_ENC_DIV_FCLK_SEL,


	// Unique bit field registers for R64 CON17.

#ifdef OLD_TIMING_GENERATOR

	REG_FREE_RUN_RATE,
	REG_FREE_RUN_HI,

#else

	REG_NTG_RATE,		
	REG_NTG_ONESHOT,	
	REG_NTG_TRIG_MODE,

#endif

	// Unique bit field registers for R64 CON18.

	REG_ALPF,
	REG_TOP_REV,

#ifdef OLD_TIMING_GENERATOR

	REG_SIG_GEN_POL,
	REG_SCALE_BY8K,

#else

	REG_NTG_INVERT,		
	REG_NTG_TIME_MODE,	

#endif

	// Unique bit field registers for R64 CON19.

	REG_LINES_TOGO,
	REG_UART_MUTEX,
	REG_ENC_DIV_N,
	REG_VFG_MBOX,

	// Unique bit field registers for R64 CON20.

	REG_FIFO_EQ,
	REG_VID_BRL,
	REG_VIDEO_2DPM,
	REG_COLOR_MASK,
	REG_SHIFT_DSP_SELECT,
	REG_SHIFT_DSP,
	REG_SHIFT_DSP_LEFT,

	// Unique bit field registers for R64 CON21.

	REG_RED_GAIN,
	REG_GREEN_GAIN,
	REG_BLUE_GAIN,
	REG_DECODER_OUT,
	REG_BAYER_RAW_DEPTH,
	REG_DECODER_PHASE,

	// Unique bit field registers for R64 CON22.

	REG_DEST_ADD,

	// Unique bit field registers for Karbon CON22.

	REG_SCAN_STEP,
	REG_FLASH_DATA,


	// Unique bit field registers for R64 CON23.

	REG_DPM_SIZE,
	REG_CTAB_INT_CON,
	REG_LINES_PER_INT,

	// Unique bit field registers for R64 CON24 (not in all MUX files)
	
	REG_LUT_HOST_DATA,		
	REG_LUT_ON,				
	REG_LUT_HOST_ADDR,		
	REG_LUT_BANK,
	REG_LUT_DATA_WRITE_SEL,
	REG_LUT_HOST_LANE,		
	REG_LUT_WEN,
	REG_LUT_HOST_ACCESS,			

	// Unique bit field registers for R64 CON25.

	REG_DELAY_TAP1,
	REG_DELAY_TAP1_SEL,
	REG_FW_MODE,

#ifndef OLD_TIMING_GENERATOR
	
	// Unique bit field registers for R64 CON26.

	REG_NTG_EXPOSURE,
	REG_NTG_RESET,
	REG_NTG_SLAVE,

#endif
	
	// Unique bit field registers for Karbon CON27.

	REG_FLASH_ADDR,	
	REG_FLASH_WP,	
	REG_FLASH_RST,	
	REG_FLASH_BE,	
	REG_FLASH_CE,	
	REG_FLASH_OE,	
	REG_FLASH_WE,	


	// Unique bit field registers for R64/Karbon CON28.

	REG_FIRST_QUAD_PTR_LO,

	// Unique bit field registers for R64/Karbon CON29.

	REG_FIRST_QUAD_PTR_HI,

	// Unique bit field registers for R64/Karbon CON30.

	REG_CHAIN_DATA_SIZE_LO,

	// Unique bit field registers for R64/Karbon CON31.

	REG_CHAIN_DATA_SIZE_HI,

	// Unique bit field registers for R64/Karbon CON32.

	REG_CHAIN_DATA_TOGO_LO,

	// Unique bit field registers for R64/Karbon CON33.

	REG_CHAIN_DATA_TOGO_HI,

	// Unique bit field registers for R64/Karbon CON34 (old CON32).

	REG_DMA_AUTO_START,
	REG_DMA_ABORT,
	REG_DMA_DIRECTION,
	REG_DMA_DONE,
	REG_DMA_STATUS,
	REG_DMA_NO_RULE,
	REG_DMA_INIT_FUNC,
	REG_DMA_PRIORITY,
	REG_DMA_64_BIT,
	REG_DMA_CHAINING,
	REG_DMA_COMMAND,
	REG_DMA_BEN,
	REG_LATCH_CONTROL,

	// Unique bit field registers for R64/Karbon CON35 (old CON33).

	REG_XFR_PER_INT,

	// Unique bit field registers for Neon CON36 (old CON34).

	REG_MEM_ADDR_LO,

	// Unique bit field registers for Neon CON37 (old CON35).

	REG_MEM_ADDR_HI,
	REG_MEM_CS,
	REG_MEM_WRITE,
	REG_DWNLD_MODE,
	REG_MEM_DATA,

	// Unique bit field registers for Neon CON38 (old CON36).

	REG_POCL_POWER_ON,
	REG_POCL_GND_ON,
	REG_POCL_CLOCK_WAIT,
	REG_POCL_SENSE,
	REG_POCL_CLK_DETECTED,
	REG_POCL_DETECTED,
	REG_POCL_EN,

	// Unique bit field registers for Alta CON40.

	REG_AFE_PORT_ADDR,	
	REG_AFE_PORT_WRITE,
	REG_AFE_PORT_ACCESS,

	// Unique bit field registers for Alta CON41.

	REG_AFE_PORT_DATA,	
	REG_AFE_PORT_BUSY,	
	REG_AFE_PORT_ERROR,
	REG_AFE_PORT_RESET,

	// Unique bit field registers for Alta CON42.

//	REG_FI,				
	REG_FIRST_FI,		
	REG_RD_WEN,			
	REG_RD_HD,			
	REG_RD_VD,			
	REG_SWAP_LINES,		
	REG_FI_POL,			
	REG_SOE,			
	REG_ACQ_IV,			
	REG_FEN_SEL,		
	REG_HD_SEL,			
	REG_VD_SEL,			
	REG_GEN_IV,			
	REG_MID,

	// Unique bit field registers for Alta CON43.

	REG_GEN_H_PERIOD,	
	REG_GEN_H_LOW,		

	// Unique bit field registers for Alta CON44.

	REG_GEN_V_PERIOD,	
	REG_GEN_V_LOW,		

	// unique bit field register for Karbon/Neon CON51
	REG_QENC_COUNT,		
	REG_QENC_PHASEA,	
	REG_QENC_PHASEB,	
	REG_QENC_DIR,		
	REG_QENC_INTRVL_IN,	
	REG_QENC_NEW_LINES,

	// Unique bit field registers for R64 pseueo software register SOFT0.

	REG_VID_WALK,

	// Unique bit field registers for R64 RO_INFOHI.

	REG_INFOHI,

	// Unique bit field registers for R64 RO_INFOLO.

	REG_INFOLO,

	// PCI 9080 global configuration bit field registers.

	REG_CFG_VENDOR,
	REG_CFG_DEVICE,

	REG_CFG_IO_ACCESS,
	REG_CFG_MEM_ACCESS,
	REG_CFG_BUS_MASTER,
	REG_CFG_SPECIAL,
	REG_CFG_MEM_WRITE,
	REG_CFG_VGA_SNOOP,
	REG_CFG_PARITY,
	REG_CFG_STEPPING,
	REG_CFG_SERR,
	REG_CFG_ANY_AGENT,

	REG_CFG_UDF,
	REG_CFG_FAST_BACK,
	REG_CFG_PARITY_ERR,
	REG_CFG_DEVSEL_TIM,
	REG_CFG_TARG_ABORT_SIG,
	REG_CFG_TARG_ABORT_RCV,
	REG_CFG_MAST_ABORT_RCV,
	REG_CFG_SERR_SIG,
	REG_CFG_PCI_PARITY_ERR,

	REG_CFG_REV_ID,
	REG_CFG_SPECIFIC,
	REG_CFG_SUB_CLASS,
	REG_CFG_BASE_CLASS,

	REG_CFG_CACHE_SIZE,
	REG_CFG_BURST_CLOCKS,
	REG_CFG_HEADER_TYPE,
	REG_CFG_MULTIPLE,
	REG_CFG_DEV_FAIL,
	REG_CFG_BIST_GO,
	REG_CFG_BIST_SUPPORT,

	REG_CFG_MEM_MAP_TO_IO,
	REG_CFG_MEM_REG_LOC,
	REG_CFG_MEM_PREFETCH,
	REG_CFG_MEM_ADDR,

	REG_CFG_IO_MAP_TO_IO,
	REG_CFG_IO_ADDR,

	REG_CFG_LOC_MAP_TO_IO,
	REG_CFG_LOC_REG_LOC,
	REG_CFG_LOC_PREFETCH,
	REG_CFG_LOC_ADDR,

	REG_CFG_LOC1_MAP_TO_IO,
	REG_CFG_LOC1_REG_LOC,
	REG_CFG_LOC1_PREFETCH,
	REG_CFG_LOC1_ADDR,

	REG_CFG_SUB_VENDOR_ID,
	REG_CFG_SUB_ID,

	REG_CFG_ROM_ACCESS,
	REG_CFG_ROM_ADDR,

	REG_CFG_INT_LINE,
	REG_CFG_INT_PIN,
	REG_CFG_BURST_PERIOD,
	REG_CFG_BURST_LATENCY,

	// PCI 9080 local configuration bit field registers.

	REG_P0TOL_IO_MAP,
	REG_P0TOL_MEM_LOC,
	REG_P0TOL_MEM_PFETCH,
	REG_P0TOL_MEM_MASK,

	REG_P0TOL_MAP_ENABLE,
	REG_P0TOL_MEM_REPLACE,

	REG_MA_LOC_LATENCY_CLKS,
	REG_MA_LOC_PAUSE_CLKS,
	REG_MA_LOC_LATENCY,
	REG_MA_LOC_PAUSE,
	REG_MA_LOC_BREQ,
	REG_MA_DMA_PRIORITY,
	REG_MA_GIVE_UP,
	REG_MA_LOCK,
	REG_MA_REQ_MODE,
	REG_MA_PCI_REV_21,
	REG_MA_NO_WRITE,
	REG_MA_READ_FLUSH,
	REG_MA_GATE_LATENCY,
	REG_MA_READ_AHEAD,
	REG_MA_GET_SUB_ID,

	REG_BE_LOC_CFG,
	REG_BE_DIRECT_MASTER,
	REG_BE_DIRECT_SLAVE,
	REG_BE_DIRECT_SLAVE_ROM,
	REG_BE_BYTE_LANE,
	REG_BE_DIRECT_SLAVE_1,
	REG_BE_DMA_CHAN1,
	REG_BE_DMA_CHAN0,

	REG_PTOL_ROM_MASK,

	REG_PTOL_ROM_DELAY,
	REG_PTOL_ROM_BREQ,
	REG_PTOL_ROM_CLOCKS,
	REG_PTOL_ROM_REPLACE,

	REG_P0TOL_LOC_BUS_WIDTH,
	REG_P0TOL_LOC_MEM_WAIT,
	REG_P0TOL_LOC_MEM_READY,
	REG_P0TOL_LOC_MEM_BTERM,
	REG_P0TOL_LOC_MEM_PREF_OFF,
	REG_P0TOL_LOC_ROM_PREF_OFF,
	REG_P0TOL_LOC_MEM_COUNT_ON,
	REG_P0TOL_LOC_MEM_COUNT,
	REG_P0TOL_LOC_MEM_ONE_READ,
	REG_P0TOL_LOC_ROM_WIDTH,
	REG_P0TOL_LOC_ROM_WAIT,
	REG_P0TOL_LOC_ROM_READY,
	REG_P0TOL_LOC_ROM_BTERM,
	REG_P0TOL_LOC_MEM_BURST,
	REG_P0TOL_LOC_LONG_LOAD,
	REG_P0TOL_LOC_ROM_BURST,
	REG_P0TOL_LOC_FIFO_TRDY,
	REG_P0TOL_LOC_RETRY,

	REG_LTOP_MASK,

	REG_LTOP_MEMORY_BASE,

	REG_LTOP_IOCFG_BASE,

	REG_LTOP_DM_MEM,
	REG_LTOP_DM_IO,
	REG_LTOP_DM_LOCK,
	REG_LTOP_DM_PFETCH,
	REG_LTOP_DM_IRDY,
	REG_LTOP_DM_FIFO_ALARM,
	REG_LTOP_DM_WRITE_INVAL,
	REG_LTOP_DM_FIFO_ALARM_HI,
	REG_LTOP_DM_PREFETCH_LIMIT,
	REG_LTOP_DM_PFETCH_HI,
	REG_LTOP_DM_ZEROS,
	REG_LTOP_DM_DELAY,
	REG_LTOP_REPLACE,

	REG_LTOP_IOCFG_TYPE,
	REG_LTOP_IOCFG_REG,
	REG_LTOP_IOCFG_FUNC,
	REG_LTOP_IOCFG_DEVICE,
	REG_LTOP_IOCFG_BUS,
	REG_LTOP_IOCFG_ENABLE,

	REG_P1TOL_IO_MAP,
	REG_P1TOL_MEM_LOC,
	REG_P1TOL_MEM_PFETCH,
	REG_P1TOL_MEM_MASK,

	REG_P1TOL_MAP_ENABLE,
	REG_P1TOL_MEM_REPLACE,

	REG_P1TOL_LOC_BUS_WIDTH,
	REG_P1TOL_LOC_MEM_WAIT,
	REG_P1TOL_LOC_MEM_READY,
	REG_P1TOL_LOC_MEM_BTERM,
	REG_P1TOL_LOC_MEM_BURST,
	REG_P1TOL_LOC_MEM_PREF_OFF,
	REG_P1TOL_LOC_MEM_COUNT_ON,
	REG_P1TOL_LOC_MEM_COUNT,

	// PCI 9080 shared run time bit field registers.

	REG_LSERR_ABORT,
	REG_LSERR_PARITY,
	REG_SERR_GEN,
	REG_MAIL_INT,
	REG_PCI_INT,
	REG_PCI_INT_DOORBELL,
	REG_PCI_INT_ABORT,
	REG_PCI_INT_LOCAL,
	REG_RETRY_ABORT,
	REG_PCI_ACT_DOORBELL,
	REG_PCI_ACT_ABORT,
	REG_PCI_ACT_LOCAL,
	REG_LOC_INT,
	REG_LOC_INT_DOORBELL,
	REG_LOC_INT_DMA0,
	REG_LOC_INT_DMA1,
	REG_LOC_ACT_DOORBELL,
	REG_LOC_ACT_DMA0,
	REG_LOC_ACT_DMA1,
	REG_LOC_ACT_BIST,
	REG_ABT_LOW_BM_DM,
	REG_ABT_LOW_BM_DMA0,
	REG_ABT_LOW_BM_DMA1,
	REG_ABT_LOW_RETRY,
	REG_MAIL_TO_0,
	REG_MAIL_TO_1,
	REG_MAIL_TO_2,
	REG_MAIL_TO_3,

	REG_PCI_COM_DMA_READ,
	REG_PCI_COM_DMA_WRITE,
	REG_PCI_COM_DMA_DM_READ,
	REG_PCI_COM_DMA_DM_WRITE,
	REG_PCI_COM_USERO,
	REG_PCI_COM_USERI,
	REG_PROM_CLOCK,
	REG_PROM_SELECT,
	REG_PROM_BIT_WRITE,
	REG_PROM_BIT_READ,
	REG_PROM_I_SEE_YOU,
	REG_PCI_CONFIG_RELOAD,
	REG_PCI_RESET,
	REG_LOC_INIT_DONE,

	REG_PCI_PLX_VENDOR,
	REG_PCI_PLX_DEVICE,

	REG_PCI_PLX_REVISION,

	// PCI 9080 Local DMA bit field registers.

	REG_DMA_CH0_BUS_WIDTH,
	REG_DMA_CH0_MEM_WAIT,
	REG_DMA_CH0_MEM_READY,
	REG_DMA_CH0_MEM_BTERM,
	REG_DMA_CH0_BURST,
	REG_DMA_CH0_CHAINING,
	REG_DMA_CH0_INT_DONE,
	REG_DMA_CH0_CONST_ADDR,
	REG_DMA_CH0_DEMAND,
	REG_DMA_CH0_WRITE_INVAL,
	REG_DMA_CH0_EOT_ENABLE,
	REG_DMA_CH0_STOP,
	REG_DMA_CH0_CLEAR,
	REG_DMA_CH0_INT_SELECT,

	REG_DMA_CH0_EOX_LOW,
	REG_DMA_CH0_BANK_LOW,
	REG_DMA_CH0_BYPASS_LOW,
	REG_DMA_CH0_MCHSEL_LOW,
	REG_DMA_CH0_FLUSH_LOW,
	REG_DMA_CH0_ADDR,
	REG_DMA_CH0_EOX_HI,
	REG_DMA_CH0_BANK_HI,
	REG_DMA_CH0_BYPASS_HI,
	REG_DMA_CH0_MCHSEL_HI,
	REG_DMA_CH0_FLUSH_HI,

	REG_DMA_CH0_BY8_LOW,				// RoadRunner only.
	REG_DMA_CH0_BY8_HI,					// RoadRunner only.

	REG_DMA_CH0_CHAN_LOW,				// Raven only.
	REG_DMA_CH0_CHAN_HI,				// Raven only.

	REG_DMA_CH1_CHAN_LOW,				// Raven only.
	REG_DMA_CH1_EOX_LOW,				// Raven only.
	REG_DMA_CH1_BANK_LOW,				// Raven only.
	REG_DMA_CH1_BYPASS_LOW,				// Raven only.
	REG_DMA_CH1_MCHSEL_LOW,				// Raven only.
	REG_DMA_CH1_FLUSH_LOW,				// Raven only.
	REG_DMA_CH1_ADDR,					// Raven only.
	REG_DMA_CH1_CHAN_HI,				// Raven only.
	REG_DMA_CH1_EOX_HI,					// Raven only.
	REG_DMA_CH1_BANK_HI,				// Raven only.
	REG_DMA_CH1_BYPASS_HI,				// Raven only.
	REG_DMA_CH1_MCHSEL_HI,				// Raven only.
	REG_DMA_CH1_FLUSH_HI,				// Raven only.

	REG_DMA_CH0_TSIZE,

	REG_DMA_CH0_DESC_PCI_SPACE,
	REG_DMA_CH0_DESC_CHAIN_END,
	REG_DMA_CH0_DESC_COUNT_INT,
	REG_DMA_CH0_DESC_TRAN_LTOP,
	REG_DMA_CH0_DESC_NEXT,

	REG_DMA_CH1_BUS_WIDTH,
	REG_DMA_CH1_MEM_WAIT,
	REG_DMA_CH1_MEM_READY,
	REG_DMA_CH1_MEM_BTERM,
	REG_DMA_CH1_BURST,
	REG_DMA_CH1_CHAINING,
	REG_DMA_CH1_INT_DONE,
	REG_DMA_CH1_CONST_ADDR,
	REG_DMA_CH1_DEMAND,
	REG_DMA_CH1_WRITE_INVAL,
	REG_DMA_CH1_EOT_ENABLE,
	REG_DMA_CH1_STOP,
	REG_DMA_CH1_CLEAR,
	REG_DMA_CH1_INT_SELECT,

	REG_DMA_CH1_TSIZE,

	REG_DMA_CH1_DESC_PCI_SPACE,
	REG_DMA_CH1_DESC_CHAIN_END,
	REG_DMA_CH1_DESC_COUNT_INT,
	REG_DMA_CH1_DESC_TRAN_LTOP,
	REG_DMA_CH1_DESC_NEXT,

	REG_DMA_COM_CH0_TRAN,
	REG_DMA_COM_CH0_GO,
	REG_DMA_COM_CH0_ABORT,
	REG_DMA_COM_CH0_INT_CLEAR,
	REG_DMA_COM_CH0_DONE,
	REG_DMA_COM_CH1_TRAN,
	REG_DMA_COM_CH1_GO,
	REG_DMA_COM_CH1_ABORT,
	REG_DMA_COM_CH1_INT_CLEAR,
	REG_DMA_COM_CH1_DONE,

	REG_DA_LOC_LATENCY_CLKS,
	REG_DA_LOC_PAUSE_CLKS,
	REG_DA_LOC_LATENCY,
	REG_DA_LOC_PAUSE,
	REG_DA_LOC_BREQ,
	REG_DA_DMA_PRIORITY,
	REG_DA_GIVE_UP,
	REG_DA_LOCK,
	REG_DA_REQ_MODE,
	REG_DA_PCI_REV_21,
	REG_DA_NO_WRITE,
	REG_DA_READ_FLUSH,
	REG_DA_GATE_LATENCY,
	REG_DA_READ_AHEAD,
	REG_DA_GET_SUB_ID,

	REG_DT_CH0_PTOL_AFULL,
	REG_DT_CH0_LTOP_AEMPTY,
	REG_DT_CH0_LTOP_AFULL,
	REG_DT_CH0_PTOL_AEMPTY,
	REG_DT_CH1_PTOL_AFULL,
	REG_DT_CH1_LTOP_AEMPTY,
	REG_DT_CH1_LTOP_AFULL,
	REG_DT_CH1_PTOL_AEMPTY,

	// QuickLogic QL5064 bit field registers.

	REG_WRITE0_ADDR_LO,

	REG_WRITE0_ADDR_HI,

	REG_WRITE0_COUNT_REQ,

	REG_WRITE0_COUNT_REM,

	REG_WRITE1_ADDR_LO,

	REG_WRITE1_ADDR_HI,

	REG_WRITE1_COUNT_REQ,

	REG_WRITE1_COUNT_REM,

	REG_USER_REV,
	REG_CHIP_REV,
	REG_RCV0_LOW,
	REG_RCV0_EMPTY,
	REG_RCV1_LOW,
	REG_RCV1_EMPTY,
	REG_XMT0_HIGH,
	REG_XMT0_FULL,
	REG_XMT1_HIGH,
	REG_XMT1_FULL,

	REG_XMT1_NOT_EMPTY,
	REG_XMT0_NOT_EMPTY,
	REG_RCV1_PENDING,
	REG_RCV0_PENDING,
	REG_XMT1_PENDING,
	REG_XMT0_PENDING,

	REG_BAR0_BURST,
	REG_BAR1_BURST,
	REG_BAR2_BURST,
	REG_BAR3_BURST,
	REG_BAR4_BURST,
	REG_BAR5_BURST,
	REG_ROM_BURST,
	REG_BAR0_PREFETCH,
	REG_BAR1_PREFETCH,
	REG_BAR2_PREFETCH,
	REG_BAR3_PREFETCH,
	REG_BAR4_PREFETCH,
	REG_BAR5_PREFETCH,
	REG_ROM_PREFETCH,
	REG_BAR0_THRESH,
	REG_BAR1_THRESH,
	REG_BAR2_THRESH,
	REG_BAR3_THRESH,
	REG_BAR4_THRESH,
	REG_BAR5_THRESH,
	REG_TARGET_THRESH,

	REG_BAR0_CONFIG,
	REG_BAR1_CONFIG,
	REG_BAR2_CONFIG,
	REG_BAR3_CONFIG,
	REG_BAR4_CONFIG,
	REG_BAR5_CONFIG,
	REG_BAR0_ENABLE,
	REG_BAR1_ENABLE,
	REG_BAR2_ENABLE,
	REG_BAR3_ENABLE,
	REG_BAR4_ENABLE,
	REG_BAR5_ENABLE,
	REG_ROM_ENABLE,
	REG_WAIT_WRITE,
	REG_WAIT_READ,
	REG_WAIT_BURST,

	REG_I2O_INT_REQ,
		
	REG_I2O_INT_MASK,

	REG_I2O_QUEUE_IN,

	REG_I2O_QUEUE_OUT,

	REG_READ0_ADDR_LO,

	REG_READ0_ADDR_HI,

	REG_READ0_COUNT_REQ,

	REG_READ0_COUNT_REM,

	REG_READ1_ADDR_LO,

	REG_READ1_ADDR_HI,

	REG_READ1_COUNT_REQ,

	REG_READ1_COUNT_REM,

	REG_RCV0_LOW_THRESH,
	REG_RCV1_LOW_THRESH,
	REG_RCV0_HIGH_THRESH,
	REG_RCV1_HIGH_THRESH,

	REG_XMT0_LOW_THRESH,
	REG_XMT1_LOW_THRESH,
	REG_XMT0_HIGH_THRESH,
	REG_XMT1_HIGH_THRESH,

	REG_MAIL0_OUT,
	REG_MAIL1_OUT,
	REG_MAIL2_OUT,
	REG_MAIL3_OUT,

	REG_MAIL4_OUT,
	REG_MAIL5_OUT,
	REG_MAIL6_OUT,
	REG_MAIL7_OUT,

	REG_MAIL0_IN,
	REG_MAIL1_IN,
	REG_MAIL2_IN,
	REG_MAIL3_IN,

	REG_MAIL4_IN,
	REG_MAIL5_IN,
	REG_MAIL6_IN,
	REG_MAIL7_IN,

	REG_INT_PCI_OMB_EMPTY,
	REG_INT_PCI_IMB_FULL,
	REG_INT_XMT0,
	REG_INT_XMT1,
	REG_INT_RCV0,
	REG_INT_RCV1,
	REG_INT_CHAIN_DONE,
	REG_INT_CHAIN_LAST,
	REG_INT_USER,

	REG_ENINT_PCI_OMB_FULL,
	REG_ENINT_PCI_IMB_EMPTY,

	REG_ENINT_PCI_OMB_EMPTY,
	REG_ENINT_PCI_IMB_FULL,
	REG_ENINT_XMT0,
	REG_ENINT_XMT1,
	REG_ENINT_RCV0,
	REG_ENINT_RCV1,
	REG_ENINT_CHAIN_DONE,
	REG_ENINT_CHAIN_LAST,
	REG_ENINT_USER,

	REG_PCI_OMB_FULL,
	REG_PCI_IMB_FULL,
	REG_XMT0_START,
	REG_XMT1_START,
	REG_RCV0_START,
	REG_RCV1_START,
	REG_CHAIN_START,
	REG_CHAIN_NO_EOC,
	REG_I2O_IFL_EMPTY,
	REG_I2O_IPL_FULL,
	REG_I2O_OPL_EMPTY,
	REG_I2O_OFL_FULL,

	REG_XMT0_ERROR,
	REG_XMT1_ERROR,
	REG_RCV0_ERROR,
	REG_RCV1_ERROR,
	REG_CHAIN_ERROR,
	REG_SPCI_ERROR,
	REG_PCI_TARGET_ABORT,
	REG_PCI_MASTER_ABORT,
	REG_PCI_RETRY_TIMEOUT,
	REG_PCI_PARITY_ERROR,

	REG_LAT_TIMEOUT_DISABLE,
	REG_FIFO_THRESHOLD,
	REG_MAX_RETRY,
	REG_XMT_BYTE_ENABLES,
	REG_XMT0_CANCEL,
	REG_XMT1_CANCEL,
	REG_RCV0_CANCEL,
	REG_RCV1_CANCEL,
	REG_CHAIN_CANCEL,
	REG_XMT0_FLUSH,
	REG_XMT1_FLUSH,
	REG_RCV0_SPECIAL_ENABLE,
	REG_RCV1_SPECIAL_ENABLE,

	REG_XMT0_FORCE32,
	REG_XMT1_FORCE32,
	REG_RCV0_FORCE32,
	REG_RCV1_FORCE32,
	REG_XMT0_ARB,
	REG_XMT1_ARB,
	REG_RCV0_ARB,
	REG_RCV1_ARB,
	REG_MASTER_ARB,

	REG_RESET_TOTAL,

	REG_RESET_FPGA,

	// Indirect Address/Port register for Raven's Brooktree chip.

	// Brooktree BT_CMND0.

	REG_VOUTC,
	REG_VOUTY,

	// Brooktree BT_CMND2.

	REG_COLORSTAT,
	REG_COVERFLOW,
	REG_YOVERFLOW,
	REG_VIDSTABLE,
	REG_VIDPRES,

	// Brooktree BT_CMND3.

	REG_GAMAREMOVE,
	REG_COLORFORMAT,

	// Brooktree BT_CMND4.

	REG_LOWCOLOR,
	REG_CHROMAAGC,
	REG_AGC,
	REG_COLORBAR,
	REG_POWERDOWN,

	// Brooktree BT_CMND5,

	REG_MONOSRC,
	REG_NUMSYNCPULSES,
	REG_LPF,
	REG_BLACKLEVEL,
	REG_CHROMAMOD,
	REG_YC,

	// Brooktree BT_CMND6.

	REG_XTALSEL,

	// Brooktree BT_CMND7.

	REG_CONTOUTEN,
	REG_PIXOUTEN,
	REG_CAPTSTAT,
	REG_FRAMESTROBE,
	REG_FIELDSTROBE,

	// Brooktree BT_BRIGHTNESS.

	REG_BRIGHTNESS,

	// Brooktree BT_CONTRAST.

	REG_CONTRAST,

	// Brooktree BT_SATURATION.

	REG_SATURATION,

	// Brooktree BT_HUE.

	REG_HU,

	// Brooktree BT_HCLOCK.

	REG_HCLOCK,

	// Brooktree BT_HDELAY.

	REG_HDELAY,

	// Brooktree BT_ACTIVEPIX.

	REG_ACTIVEPIX,

	// Brooktree BT_VDELAY.

	REG_VDELAY,

	// Brooktree BT_ACTIVELINES.

	REG_ACTIVELINES,

	// Brooktree BT_SCFREQ.

	REG_SCFREQ,

	// Brooktree BT_AGCDELAY.

	REG_AGCDELAY,

	// Brooktree BT_BURSTDELAY.

	REG_BURSTDELAY,

	// Brooktree BT_SAMPLERATE.

	REG_SAMPLERATE,

	// Brooktree BT_POLARITY.

	REG_VACTIVE,
	REG_VRESETPOL,
	REG_HACTIVEPOL,
	REG_HRESETPOL,
	REG_ACTIVEPOL,
	REG_VALIDPOL,

	// Brooktree BT_RESET.

	REG_SOFTRESET,


	// Narrow < 32-bit wide Alta-AN AFE indirect address/data port registers 

	REG_DEV_REV,				
	REG_DEV_ID,					

	REG_HSYNC1_ACTIVE,			
	REG_HSYNC2_ACTIVE,			
	REG_VSYNC1_ACTIVE,			
	REG_VSYNC2_ACTIVE,			
	REG_SOG1_ACTIVE,			
	REG_SOG2_ACTIVE,			
	REG_PLL_LOCKED,				
	REG_CSYNC_DETECTED,			

	REG_HSYNC1_POL,				
	REG_HSYNC2_POL,				
	REG_VSYNC1_POL,				
	REG_VSYNC2_POL,				
	REG_HSYNC1_TRI_LEVEL,		
	REG_HSYNC2_TRI_LEVEL,		

	REG_HSYNC1_TRESH,			
	REG_HSYNC2_TRESH,			
	REG_DISABLE_GLITCH,			

	REG_SOG12_THRESH,			
	REG_SOG_FILTER,				
	REG_SOG_HYSTER_DIS,			

	REG_CHAN_SEL,				
	REG_INPUT_COUPLING,			
	REG_YPBPR_INPUTS,			
	REG_SYNC_TYPE,				
	REG_COMP_SYNC_SRC,			
	REG_COAST_CLAMP_EN,			
	REG_SYNC_MASK_DIS,			
	REG_HSYNC_OUT_MASK_DIS,		

	REG_RED_CHAN_GAIN,				

	REG_GREEN_CHAN_GAIN,				

	REG_BLUE_CHAN_GAIN,				

	REG_RED_CHAN_OFFSET,				

	REG_GREEN_CHAN_OFFSET,			

	REG_BLUE_CHAN_OFFSET,			

	REG_OFFSET_DAC_RANGE,		
	REG_RED_OFFSET_DAC_LSB,		
	REG_GREEN_OFFSET_DAC_LSB,	
	REG_BLUE_OFFSET_DAC_LSB,	

	REG_BANDWIDTH,			
	REG_PEAKING,			

	REG_PLL_H_TOTAL_MSB,		

	REG_PLL_H_TOTAL_LSB,		

	REG_PLL_SAMPLE_PHASE,		

	REG_PLL_PRE_COAST,			

	REG_PLL_POST_COAST,			

	REG_PLL_HSYNC1_LOCK_EDGE,	
	REG_PLL_HSYNC2_LOCK_EDGE,	
	REG_CLKINV_IN_PIN_DIS,		
	REG_CLKINV_IN_PIN_FUNC,		
	REG_XCLK_OUT_FREQ,			
	REG_XCLK_OUT_DIS,			

	REG_DC_RSTR_PIX_MSB,		

	REG_DC_RSTR_PIX_LSB,		

	REG_DC_REST_CLAMP_WIDTH,	

	REG_ABLC_DIS,				
	REG_ABLC_PIX_WIDTH,			
	REG_ABLC_BANDWIDTH,			

	REG_OUT_BUS_WIDTH,			
	REG_OUT_INTERLEAVE,			
	REG_OUT_BUS_SWAP,			
	REG_OUT_UV_ORDER,			
	REG_OUT_422_MODE,			
	REG_DATACLK_POL,			
	REG_VSOUT_POL,				
	REG_HSOUT_POL,				

	REG_HSOUT_WIDTH,			

	REG_RP_OUT_TRI,				
	REG_RS_OUT_TRI,				
	REG_GP_OUT_TRI,				
	REG_GS_OUT_TRI,				
	REG_BP_OUT_TRI,				
	REG_BS_OUT_TRI,				
	REG_DATACLK_NOT_TRI,		
	REG_DATACLK_TRI,			

	REG_RED_PWR_DOWN,			
	REG_GREEN_PWR_DOWN,			
	REG_BLUE_PWR_DOWN,			
	REG_PLL_PWR_DOWN,			

	REG_PLL_TUNING,				

	REG_RED_ABLC_TARGET,		

	REG_GREEN_ABLC_TARGET,		

	REG_BLUE_ABLC_TARGET,		

	REG_DC_RSTR_CLAMP_IMP,		

	REG_OUT_SYNC_TRI,			
	REG_COAST_POL,				
	REG_HSOUT_LOCK_EDGE,		
	REG_VSYNCOUT_MODE,			
	REG_VSOUT_MODE,				

	// Narrow < 32-bit wide Alta-CO AFE indirect address/data port registers 

	REG_INSEL,				
	REG_VID_SEL,			

	REG_ENVSPROC,			
	REG_BETACAM,			
	REG_ENHSPLL,			

	REG_SD_DUP_AV,			
	REG_OF_SEL,				
	REG_TOD,				
	REG_VBI_EN,				

	REG_RANGE,				
	REG_EN_SFL_PI,			
	REG_BL_C_VBI,			
	REG_TIM_OE,				
	REG_BT656_4,			

	REG_AD_PAL_EN,			
	REG_AD_NTSC_EN,			
	REG_AD_PALM_EN,			
	REG_AD_PALN_EN,			
	REG_AD_P60_EN,			
	REG_AD_N443_EN,			
	REG_AD_SECAM_EN,		
	REG_AD_SEC525_EN,		

	REG_CON,				

	REG_BRI,				

	REG_HUE,				

	REG_DEF_VAL_EN,			
	REG_DEF_VAL_AUTO_EN,	
	REG_DEF_Y,				

	REG_DEF_C,				

	REG_SUB_USR_EN,			

	REG_PDBP,				
	REG_PWRDN,				
	REG_RES,				

	REG_IN_LOCK,			
	REG_LOST_LOCK,			
	REG_FSC_LOCK,			
	REG_FOLLOW_PW,			
	REG_AD_RESULT,			
	REG_COL_KILL,			

	REG_IDENT,				

	REG_MVCS_DET,			
	REG_MVCS_T3,			
	REG_MV_PS_DET,			
	REG_MV_AGC_DET,			
	REG_LL_NSTD,			
	REG_FSC_NSTD,			

	REG_INST_HLOCK,			
	REG_GEMD,				
	REG_SD_OP_50_HZ,		
	REG_FREE_RUN_ACT,		
	REG_STD_FLD_LEN,		
	REG_INTERLACE,			
	REG_PAL_SW_LOCK,		

	REG_CCLEN,				

	REG_DCT,				

	REG_CSFM,				
	REG_YSFM,				

	REG_WYSFM,				
	REG_WYSFMOVR,			

	REG_PSFSEL,				
	REG_NSFSEL,				

	REG_VS_JIT_COMP_EN,		
	REG_EN28XTAL,			
	REG_TRI_LLC,			

	REG_LTA,				
	REG_CTA,				
	REG_AUTO_PDC_EN,		
	REG_SWPC,				

	REG_PW_UPD,				
	REG_CKE,				

	REG_CAGC,				
	REG_LAGC,				

	REG_CMG_HI,				
	REG_CAGT,				

	REG_CMG_LO,				

	REG_LMG_HI,				
	REG_LAGT,				

	REG_LMG_LO,				

	REG_HVSTIM,				
	REG_NEWAVMODE,			

	REG_VSBHE,				
	REG_VSBHO,				

	REG_VSEHE,				
	REG_VSEHO,				

	REG_HSE_HI,				
	REG_HSB_HI,				

	REG_HSB_LO,				

	REG_HSE_LO,				

	REG_PCLK,				
	REG_PF,					
	REG_PVS,				
	REG_PHS,				

	REG_YCMN,				
	REG_CCMN,				
	REG_CTAPSN,				

	REG_CTAPSP,				
	REG_CCMP,				
	REG_YCMP,				

	REG_PWRDN_ADC_2,		
	REG_PWRDN_ADC_1,		
	REG_PWRDN_ADC_0,		

	REG_CKILLTHR,			

	REG_SFL_INV,			

	REG_GDECEL_HI,			

	REG_GDECEL_LO,			

	REG_GDECOL_HI,			

	REG_GDECOL_LO,			

	REG_GDECAD,				

	REG_CTI_EN,				
	REG_CTI_AB_EN,			
	REG_CTI_AB,				
	REG_DNR_EN,				

	REG_CTI_C_TH,			

	REG_DNR_TH,				

	REG_CIL,				
	REG_COL,				
	REG_SRLS,
	REG_FSCLE,				

	REG_LLC_PAD_SEL,		

	REG_WSSD,				
	REG_CCAPD,				
	REG_EDTVD,				
	REG_CGMSD,				

	REG_WSS1,				

	REG_WSS2,				

	REG_EDTV1,				

	REG_EDTV2,				

	REG_EDTV3,				

	REG_CGMS1,				

	REG_CGMS2,				

	REG_CGMS3,				

	REG_CCAP1,				

	REG_CCAP2,				

	REG_LB_LCT,				

	REG_LB_LCM,				

	REG_LB_LCB,				

	REG_CRC_ENABLE,			

	REG_ADC0_SW,			
	REG_ADC1_SW,			

	REG_ADC2_SW,			
	REG_ADC_SW_MAN,			

	REG_LB_TH,				

	REG_LB_EL,				
	REG_LB_SL,				

	REG_SD_OFF_CB,			

	REG_SD_OFF_CR,			

	REG_SD_SAT_CB,			

	REG_SD_SAT_CR,			

	REG_NVBEG,				
	REG_NVBEGSIGN,			
	REG_NVBEGDEL_E,			
	REG_NVBEGDEL_O,			

	REG_NVEND,				
	REG_NVENDSIGN,			
	REG_NVENDDEL_E,			
	REG_NVENDDEL_O,			

	REG_NFTOG,				
	REG_NFTOGSIGN,			
	REG_NFTOGDEL_E,			
	REG_NFTOGDEL_O,			

	REG_PVBEG,				
	REG_PVBEGSIGN,			
	REG_PVBEGDEL_E,			
	REG_PVBEGDEL_O,			

	REG_PVEND,				
	REG_PVENDSIGN,			
	REG_PVENDDEL_E,			
	REG_PVENDDEL_O,			

	REG_PFTOG,				
	REG_PFTOGSIGN,			
	REG_PFTOGDEL_E,			
	REG_PFTOGDEL_O,			

	REG_DR_STR_S,			
	REG_DR_STR_C,			
	REG_DR_STR,				

	REG_IFFILTSEL,			

	REG_EXTEND_VS_MAX_FREQ,	
	REG_EXTEND_VS_MIN_FREQ,	
	REG_VS_COAST_MODE,		

	BFBitFieldCount,					// Number of registers.

	REG_UNDEFINED

} RegId;

//
// Indirect Register/Address Port Ids
//

typedef enum _IAPId
{
	// Raven Brooktree registers.
	
	IAP_BT_CMND0,
	IAP_BT_CMND2,
	IAP_BT_CMND3,
	IAP_BT_CMND4,
	IAP_BT_CMND5,
	IAP_BT_CMND6,
	IAP_BT_CMND7,
	IAP_BT_BRIGHTNESS,
	IAP_BT_CONTRAST,
	IAP_BT_SATURATION,
	IAP_BT_HUE,
	IAP_BT_HCLOCK,
	IAP_BT_HDELAY,
	IAP_BT_ACTIVEPIX,
	IAP_BT_VDELAY,
	IAP_BT_ACTIVELINES,
	IAP_BT_SCFREQ,
	IAP_BT_AGCDELAY,
	IAP_BT_BURSTDELAY,
	IAP_BT_SAMPLERATE,
	IAP_BT_POLARITY,
	IAP_BT_RESET,

	// Alta-AN AFE registers

	IAP_AFE_DEVID,	 			
	IAP_AFE_SYNC_STAT,	 		
	IAP_AFE_SYNC_POL,	 		
	IAP_AFE_HSYNC_SLICER,		
	IAP_AFE_SOG_SLICER,	 		
	IAP_AFE_IN_CNF,	 			
	IAP_AFE_RED_GAIN,	 		
	IAP_AFE_GREEN_GAIN,	 		
	IAP_AFE_BLUE_GAIN,	 		
	IAP_AFE_RED_OFFS,	 		
	IAP_AFE_GREEN_OFFS,	 		
	IAP_AFE_BLUE_OFFS,	 		
	IAP_AFE_OFFS_DAC_CNF,	 	
	IAP_AFE_BANDWIDTH,	 		
	IAP_AFE_PLL_HTOTAL_MSB,	 	
	IAP_AFE_PLL_HTOTAL_LSB,	 	
	IAP_AFE_PLL_SAMPLE_PHASE,	
	IAP_AFE_PLL_PRE_COAST,	 	
	IAP_AFE_PLL_POST_COAST,	 	
	IAP_AFE_PLL_MISC,	 		
	IAP_AFE_DC_RSTR_PIX_MSB,	
	IAP_AFE_DC_RSTR_PIX_LSB,	
	IAP_AFE_DC_RSTR_WIDTH,	 	
	IAP_AFE_ABLC_CNF,	 		
	IAP_AFE_OUT_FORMAT,	 		
	IAP_AFE_HSOUT_WIDTH,	 	
	IAP_AFE_OUT_SIG_DISABLE,	
	IAP_AFE_POWER_CON,	 		
	IAP_AFE_PLL_TUNING,	 		
	IAP_AFE_RED_ABLC,	 		
	IAP_AFE_GREEN_ABLC,	 		
	IAP_AFE_BLUE_ABLC,	 		
	IAP_AFE_DC_RSTR_CLAMP,	 	
	IAP_AFE_SYNC_SEP_CON,	 	

	// Alta-CO AFE registers

	IAP_CFE_INPUT_CTRL_00,
	IAP_CFE_VIDEO_SELECTION_01,
	IAP_CFE_RESERVED_02,
	IAP_CFE_OUTPUT_CTRL_03,
	IAP_CFE_EXTENDED_OUTPUT_CTRL_04,
	IAP_CFE_RESERVED_05,
	IAP_CFE_RESERVED_06,
	IAP_CFE_AUTODETECT_ENABLE_07,
	IAP_CFE_CONTRAST_08,
	IAP_CFE_RESERVED_09,
	IAP_CFE_BRIGHTNESS_0A,
	IAP_CFE_HUE_0B,
	IAP_CFE_DEFAULT_VALUE_Y_0C,
	IAP_CFE_DEFAULT_VALUE_C_0D,
	IAP_CFE_ADI_CTRL_0E,
	IAP_CFE_POWER_MANAGEMENT_0F,
	IAP_CFE_STATUS_1_10,
	IAP_CFE_IDENT_11,
	IAP_CFE_STATUS_2_12,
	IAP_CFE_STATUS_3_13,
	IAP_CFE_ANALOG_CLAMP_CTRL_14,
	IAP_CFE_DIGITAL_CLAMP_CTRL_1_15,
	IAP_CFE_RESERVED_16,
	IAP_CFE_SHAPING_FILTER_CTRL_17,
	IAP_CFE_SHAPING_FILTER_CTRL_2_18,	
	IAP_CFE_COMB_FILTER_CTRL_19,
	IAP_CFE_RESERVED_1A,
	IAP_CFE_RESERVED_1B,
	IAP_CFE_RESERVED_1C,
	IAP_CFE_ADI_CTRL_2_1D,
	IAP_CFE_RESERVED_1E,
	IAP_CFE_RESERVED_1F,
	IAP_CFE_RESERVED_20,
	IAP_CFE_RESERVED_21,
	IAP_CFE_RESERVED_22,
	IAP_CFE_RESERVED_23,
	IAP_CFE_RESERVED_24,
	IAP_CFE_RESERVED_25,
	IAP_CFE_RESERVED_26,
	IAP_CFE_PIXEL_DELAY_CTRL_27,
	IAP_CFE_RESERVED_28,
	IAP_CFE_RESERVED_29,
	IAP_CFE_RESERVED_2A,
	IAP_CFE_MISC_GAIN_CTRL_2B,
	IAP_CFE_AGC_MODE_CTRL_2C,
	IAP_CFE_CHROMA_GAIN_CTRL_1_2D,
	IAP_CFE_CHROMA_GAIN_CTRL_2_2E,
	IAP_CFE_LUMA_GAIN_CTRL_1_2F,
	IAP_CFE_LUMA_GAIN_CTRL_2_30,
	IAP_CFE_VSYNC_FIELD_CTRL_1_31,
	IAP_CFE_VSYNC_FIELD_CTRL_2_32,
	IAP_CFE_VSYNC_FIELD_CTRL_3_33,
	IAP_CFE_HSYNC_POSITION_CTRL_1_34,
	IAP_CFE_HSYNC_POSITION_CTRL_2_35,
	IAP_CFE_HSYNC_POSITION_CTRL_3_36,
	IAP_CFE_POLARITY_37,
	IAP_CFE_NTSC_COMB_CTRL_38,
	IAP_CFE_PAL_COMB_CTRL_39,
	IAP_CFE_ADC_CTRL_3A,
	IAP_CFE_RESERVED_3B,
	IAP_CFE_RESERVED_3C,
	IAP_CFE_MANUAL_WINDOW_CTRL_3D,
	IAP_CFE_RESERVED_3E,
	IAP_CFE_RESERVED_3F,
	IAP_CFE_RESERVED_40,
	IAP_CFE_RESAMPLE_CTRL_41,
	IAP_CFE_RESERVED_42,
	IAP_CFE_RESERVED_43,
	IAP_CFE_RESERVED_44,
	IAP_CFE_RESERVED_45,
	IAP_CFE_RESERVED_46,
	IAP_CFE_RESERVED_47,
	IAP_CFE_GEMSTAR_CTRL_1_48,
	IAP_CFE_GEMSTAR_CTRL_2_49,
	IAP_CFE_GEMSTAR_CTRL_3_4A,
	IAP_CFE_GEMSTAR_CTRL_4_4B,
	IAP_CFE_GEMSTAR_CTRL_5_4C,
	IAP_CFE_CTI_DNR_CTRL_1_4D,
	IAP_CFE_CTI_DNR_CTRL_2_4E,
	IAP_CFE_RESERVED_4F,
	IAP_CFE_CTI_DNR_CTRL_4_50,
	IAP_CFE_LOCK_COUNT_51,
	IAP_CFE_RESERVED_52,
	IAP_CFE_RESERVED_53,
	IAP_CFE_RESERVED_54,
	IAP_CFE_RESERVED_55,
	IAP_CFE_RESERVED_56,
	IAP_CFE_RESERVED_57,
	IAP_CFE_RESERVED_58,
	IAP_CFE_RESERVED_59,
	IAP_CFE_RESERVED_5A,
	IAP_CFE_RESERVED_5B,
	IAP_CFE_RESERVED_5C,
	IAP_CFE_RESERVED_5D,
	IAP_CFE_RESERVED_5E,
	IAP_CFE_RESERVED_5F,
	IAP_CFE_RESERVED_60,
	IAP_CFE_RESERVED_61,
	IAP_CFE_RESERVED_62,
	IAP_CFE_RESERVED_63,
	IAP_CFE_RESERVED_64,
	IAP_CFE_RESERVED_65,
	IAP_CFE_RESERVED_66,
	IAP_CFE_RESERVED_67,
	IAP_CFE_RESERVED_68,
	IAP_CFE_RESERVED_69,
	IAP_CFE_RESERVED_6A,
	IAP_CFE_RESERVED_6B,
	IAP_CFE_RESERVED_6C,
	IAP_CFE_RESERVED_6D,
	IAP_CFE_RESERVED_6E,
	IAP_CFE_RESERVED_6F,
	IAP_CFE_RESERVED_70,
	IAP_CFE_RESERVED_71,
	IAP_CFE_RESERVED_72,
	IAP_CFE_RESERVED_73,
	IAP_CFE_RESERVED_74,
	IAP_CFE_RESERVED_75,
	IAP_CFE_RESERVED_76,
	IAP_CFE_RESERVED_77,
	IAP_CFE_RESERVED_78,
	IAP_CFE_RESERVED_79,
	IAP_CFE_RESERVED_7A,
	IAP_CFE_RESERVED_7B,
	IAP_CFE_RESERVED_7C,
	IAP_CFE_RESERVED_7D,
	IAP_CFE_RESERVED_7E,
	IAP_CFE_RESERVED_7F,
	IAP_CFE_RESERVED_80,
	IAP_CFE_RESERVED_81,
	IAP_CFE_RESERVED_82,
	IAP_CFE_RESERVED_83,
	IAP_CFE_RESERVED_84,
	IAP_CFE_RESERVED_85,
	IAP_CFE_RESERVED_86,
	IAP_CFE_RESERVED_87,
	IAP_CFE_RESERVED_88,
	IAP_CFE_RESERVED_89,
	IAP_CFE_RESERVED_8A,
	IAP_CFE_RESERVED_8B,
	IAP_CFE_RESERVED_8C,
	IAP_CFE_RESERVED_8D,
	IAP_CFE_RESERVED_8E,
	IAP_CFE_FREE_RUN_LINE_LENGTH_1_8F,
	IAP_CFE_VBI_INFO_90,
	IAP_CFE_WSS_1_91,
	IAP_CFE_WSS_2_92,
	IAP_CFE_EDTV_1_93,
	IAP_CFE_EDTV_2_94,
	IAP_CFE_EDTV_3_95,
	IAP_CFE_CGMS_1_96,
	IAP_CFE_CGMS_2_97,
	IAP_CFE_CGMS_3_98,
	IAP_CFE_CCAP_1_99,
	IAP_CFE_CCAP_2_9A,
	IAP_CFE_LETTERBOX_1_9B,
	IAP_CFE_LETTERBOX_2_9C,
	IAP_CFE_LETTERBOX_3_9D,
	IAP_CFE_RESERVED_9E,
	IAP_CFE_RESERVED_9F,
	IAP_CFE_RESERVED_A0,
	IAP_CFE_RESERVED_A1,
	IAP_CFE_RESERVED_A2,
	IAP_CFE_RESERVED_A3,
	IAP_CFE_RESERVED_A4,
	IAP_CFE_RESERVED_A5,
	IAP_CFE_RESERVED_A6,
	IAP_CFE_RESERVED_A7,
	IAP_CFE_RESERVED_A8,
	IAP_CFE_RESERVED_A9,
	IAP_CFE_RESERVED_AA,
	IAP_CFE_RESERVED_AB,
	IAP_CFE_RESERVED_AC,
	IAP_CFE_RESERVED_AD,
	IAP_CFE_RESERVED_AE,
	IAP_CFE_RESERVED_AF,
	IAP_CFE_RESERVED_B0,
	IAP_CFE_RESERVED_B1,
	IAP_CFE_CRC_ENABLE_B2,
	IAP_CFE_RESERVED_B3,
	IAP_CFE_RESERVED_B4,
	IAP_CFE_RESERVED_B5,
	IAP_CFE_RESERVED_B6,
	IAP_CFE_RESERVED_B7,
	IAP_CFE_RESERVED_B8,
	IAP_CFE_RESERVED_B9,
	IAP_CFE_RESERVED_BA,
	IAP_CFE_RESERVED_BB,
	IAP_CFE_RESERVED_BC,
	IAP_CFE_RESERVED_BD,
	IAP_CFE_RESERVED_BE,
	IAP_CFE_RESERVED_BF,
	IAP_CFE_RESERVED_C0,
	IAP_CFE_RESERVED_C1,
	IAP_CFE_RESERVED_C2,
	IAP_CFE_ADC_SWITCH_1_C3,
	IAP_CFE_ADC_SWITCH_2_C4,
	IAP_CFE_RESERVED_C5,
	IAP_CFE_RESERVED_C6,
	IAP_CFE_RESERVED_C7,
	IAP_CFE_RESERVED_C8,
	IAP_CFE_RESERVED_C9,
	IAP_CFE_RESERVED_CA,
	IAP_CFE_RESERVED_CB,
	IAP_CFE_RESERVED_CC,
	IAP_CFE_RESERVED_CD,
	IAP_CFE_RESERVED_CE,
	IAP_CFE_RESERVED_CF,
	IAP_CFE_RESERVED_D0,
	IAP_CFE_RESERVED_D1,
	IAP_CFE_RESERVED_D2,
	IAP_CFE_RESERVED_D3,
	IAP_CFE_RESERVED_D4,
	IAP_CFE_RESERVED_D5,
	IAP_CFE_RESERVED_D6,
	IAP_CFE_RESERVED_D7,
	IAP_CFE_RESERVED_D8,
	IAP_CFE_RESERVED_D9,
	IAP_CFE_RESERVED_DA,
	IAP_CFE_RESERVED_DB,
	IAP_CFE_LETTERBOX_CTRL_1_DC,
	IAP_CFE_LETTERBOX_CTRL_2_DD,
	IAP_CFE_RESERVED_DE,
	IAP_CFE_RESERVED_DF,
	IAP_CFE_RESERVED_E0,
	IAP_CFE_SD_OFFSET_CB_E1,
	IAP_CFE_SD_OFFSET_CR_E2,
	IAP_CFE_SD_SATURATION_CB_E3,
	IAP_CFE_SD_SATURATION_CR_E4,
	IAP_CFE_NTSC_V_BIT_BEGIN_E5,
	IAP_CFE_NTSC_V_BIT_END_E6,
	IAP_CFE_NTSC_F_BIT_TOGGLE_E7,
	IAP_CFE_PAL_V_BIT_BEGIN_E8,
	IAP_CFE_PAL_V_BIT_END_E9,
	IAP_CFE_PAL_F_BIT_TOGGLE_EA,
	IAP_CFE_RESERVED_EB,
	IAP_CFE_RESERVED_EC,
	IAP_CFE_RESERVED_ED,
	IAP_CFE_RESERVED_EE,
	IAP_CFE_RESERVED_EF,
	IAP_CFE_RESERVED_F0,
	IAP_CFE_RESERVED_F1,
	IAP_CFE_RESERVED_F2,
	IAP_CFE_RESERVED_F3,
	IAP_CFE_DRIVE_STRENGTH_F4,
	IAP_CFE_RESERVED_F5,
	IAP_CFE_RESERVED_F6,
	IAP_CFE_RESERVED_F7,
	IAP_CFE_IF_COMP_CTRL_F8,
	IAP_CFE_VS_MODE_CTRL_F9,


	BFIAPCount								// Number of indirect address/port registers.

} IAPId;

//
// Indirect Register/Address Port Access Mask Ids
//

typedef enum _IAPMId
{
	// Raven Brooktree Access Masks.
	
	IAPM_BT_CMND0,
	IAPM_BT_CMND2,
	IAPM_BT_CMND3,
	IAPM_BT_CMND4,
	IAPM_BT_CMND5,
	IAPM_BT_CMND6,
	IAPM_BT_CMND7,
	IAPM_BT_BRIGHTNESS,
	IAPM_BT_CONTRAST,
	IAPM_BT_SATURATION,
	IAPM_BT_HUE,
	IAPM_BT_HCLOCK_0,
	IAPM_BT_HCLOCK_1,
	IAPM_BT_HDELAY_0,
	IAPM_BT_HDELAY_1,
	IAPM_BT_ACTIVEPIX_0,
	IAPM_BT_ACTIVEPIX_1,
	IAPM_BT_VDELAY_0,
	IAPM_BT_VDELAY_1,
	IAPM_BT_ACTIVELINES_0,
	IAPM_BT_ACTIVELINES_1,
	IAPM_BT_SCFREQ_0,
	IAPM_BT_SCFREQ_1,
	IAPM_BT_SCFREQ_2,
	IAPM_BT_AGCDELAY,
	IAPM_BT_BURSTDELAY,
	IAPM_BT_SAMPLERATE_0,
	IAPM_BT_SAMPLERATE_1,
	IAPM_BT_POLARITY,
	IAPM_BT_RESET,

	// Alta AFE Access Masks.

	IAPM_AFE_DEVID,	 			
	IAPM_AFE_SYNC_STAT,	 		
	IAPM_AFE_SYNC_POL,	 		
	IAPM_AFE_HSYNC_SLICER,		
	IAPM_AFE_SOG_SLICER,	 		
	IAPM_AFE_IN_CNF,	 			
	IAPM_AFE_RED_GAIN,	 		
	IAPM_AFE_GREEN_GAIN,	 		
	IAPM_AFE_BLUE_GAIN,	 		
	IAPM_AFE_RED_OFFS,	 		
	IAPM_AFE_GREEN_OFFS,	 		
	IAPM_AFE_BLUE_OFFS,	 		
	IAPM_AFE_OFFS_DAC_CNF,	 	
	IAPM_AFE_BANDWIDTH,	 		
	IAPM_AFE_PLL_HTOTAL_MSB,	 	
	IAPM_AFE_PLL_HTOTAL_LSB,	 	
	IAPM_AFE_PLL_SAMPLE_PHASE,	
	IAPM_AFE_PLL_PRE_COAST,	 	
	IAPM_AFE_PLL_POST_COAST,	 	
	IAPM_AFE_PLL_MISC,	 		
	IAPM_AFE_DC_RSTR_PIX_MSB,	
	IAPM_AFE_DC_RSTR_PIX_LSB,	
	IAPM_AFE_DC_RSTR_WIDTH,	 	
	IAPM_AFE_ABLC_CNF,	 		
	IAPM_AFE_OUT_FORMAT,	 		
	IAPM_AFE_HSOUT_WIDTH,	 	
	IAPM_AFE_OUT_SIG_DISABLE,	
	IAPM_AFE_POWER_CON,	 		
	IAPM_AFE_PLL_TUNING,	 		
	IAPM_AFE_RED_ABLC,	 		
	IAPM_AFE_GREEN_ABLC,	 		
	IAPM_AFE_BLUE_ABLC,	 		
	IAPM_AFE_DC_RSTR_CLAMP,	 	
	IAPM_AFE_SYNC_SEP_CON,	 	

	// Alta-CO AFE registers

	IAPM_CFE_INPUT_CTRL_00,
	IAPM_CFE_VIDEO_SELECTION_01,
	IAPM_CFE_RESERVED_02,
	IAPM_CFE_OUTPUT_CTRL_03,
	IAPM_CFE_EXTENDED_OUTPUT_CTRL_04,
	IAPM_CFE_RESERVED_05,
	IAPM_CFE_RESERVED_06,
	IAPM_CFE_AUTODETECT_ENABLE_07,
	IAPM_CFE_CONTRAST_08,
	IAPM_CFE_RESERVED_09,
	IAPM_CFE_BRIGHTNESS_0A,
	IAPM_CFE_HUE_0B,
	IAPM_CFE_DEFAULT_VALUE_Y_0C,
	IAPM_CFE_DEFAULT_VALUE_C_0D,
	IAPM_CFE_ADI_CTRL_0E,
	IAPM_CFE_POWER_MANAGEMENT_0F,
	IAPM_CFE_STATUS_1_10,
	IAPM_CFE_IDENT_11,
	IAPM_CFE_STATUS_2_12,
	IAPM_CFE_STATUS_3_13,
	IAPM_CFE_ANALOG_CLAMP_CTRL_14,
	IAPM_CFE_DIGITAL_CLAMP_CTRL_1_15,
	IAPM_CFE_RESERVED_16,
	IAPM_CFE_SHAPING_FILTER_CTRL_17,
	IAPM_CFE_SHAPING_FILTER_CTRL_2_18,	
	IAPM_CFE_COMB_FILTER_CTRL_19,
	IAPM_CFE_RESERVED_1A,
	IAPM_CFE_RESERVED_1B,
	IAPM_CFE_RESERVED_1C,
	IAPM_CFE_ADI_CTRL_2_1D,
	IAPM_CFE_RESERVED_1E,
	IAPM_CFE_RESERVED_1F,
	IAPM_CFE_RESERVED_20,
	IAPM_CFE_RESERVED_21,
	IAPM_CFE_RESERVED_22,
	IAPM_CFE_RESERVED_23,
	IAPM_CFE_RESERVED_24,
	IAPM_CFE_RESERVED_25,
	IAPM_CFE_RESERVED_26,
	IAPM_CFE_PIXEL_DELAY_CTRL_27,
	IAPM_CFE_RESERVED_28,
	IAPM_CFE_RESERVED_29,
	IAPM_CFE_RESERVED_2A,
	IAPM_CFE_MISC_GAIN_CTRL_2B,
	IAPM_CFE_AGC_MODE_CTRL_2C,
	IAPM_CFE_CHROMA_GAIN_CTRL_1_2D,
	IAPM_CFE_CHROMA_GAIN_CTRL_2_2E,
	IAPM_CFE_LUMA_GAIN_CTRL_1_2F,
	IAPM_CFE_LUMA_GAIN_CTRL_2_30,
	IAPM_CFE_VSYNC_FIELD_CTRL_1_31,
	IAPM_CFE_VSYNC_FIELD_CTRL_2_32,
	IAPM_CFE_VSYNC_FIELD_CTRL_3_33,
	IAPM_CFE_HSYNC_POSITION_CTRL_1_34,
	IAPM_CFE_HSYNC_POSITION_CTRL_2_35,
	IAPM_CFE_HSYNC_POSITION_CTRL_3_36,
	IAPM_CFE_POLARITY_37,
	IAPM_CFE_NTSC_COMB_CTRL_38,
	IAPM_CFE_PAL_COMB_CTRL_39,
	IAPM_CFE_ADC_CTRL_3A,
	IAPM_CFE_RESERVED_3B,
	IAPM_CFE_RESERVED_3C,
	IAPM_CFE_MANUAL_WINDOW_CTRL_3D,
	IAPM_CFE_RESERVED_3E,
	IAPM_CFE_RESERVED_3F,
	IAPM_CFE_RESERVED_40,
	IAPM_CFE_RESAMPLE_CTRL_41,
	IAPM_CFE_RESERVED_42,
	IAPM_CFE_RESERVED_43,
	IAPM_CFE_RESERVED_44,
	IAPM_CFE_RESERVED_45,
	IAPM_CFE_RESERVED_46,
	IAPM_CFE_RESERVED_47,
	IAPM_CFE_GEMSTAR_CTRL_1_48,
	IAPM_CFE_GEMSTAR_CTRL_2_49,
	IAPM_CFE_GEMSTAR_CTRL_3_4A,
	IAPM_CFE_GEMSTAR_CTRL_4_4B,
	IAPM_CFE_GEMSTAR_CTRL_5_4C,
	IAPM_CFE_CTI_DNR_CTRL_1_4D,
	IAPM_CFE_CTI_DNR_CTRL_2_4E,
	IAPM_CFE_RESERVED_4F,
	IAPM_CFE_CTI_DNR_CTRL_4_50,
	IAPM_CFE_LOCK_COUNT_51,
	IAPM_CFE_RESERVED_52,
	IAPM_CFE_RESERVED_53,
	IAPM_CFE_RESERVED_54,
	IAPM_CFE_RESERVED_55,
	IAPM_CFE_RESERVED_56,
	IAPM_CFE_RESERVED_57,
	IAPM_CFE_RESERVED_58,
	IAPM_CFE_RESERVED_59,
	IAPM_CFE_RESERVED_5A,
	IAPM_CFE_RESERVED_5B,
	IAPM_CFE_RESERVED_5C,
	IAPM_CFE_RESERVED_5D,
	IAPM_CFE_RESERVED_5E,
	IAPM_CFE_RESERVED_5F,
	IAPM_CFE_RESERVED_60,
	IAPM_CFE_RESERVED_61,
	IAPM_CFE_RESERVED_62,
	IAPM_CFE_RESERVED_63,
	IAPM_CFE_RESERVED_64,
	IAPM_CFE_RESERVED_65,
	IAPM_CFE_RESERVED_66,
	IAPM_CFE_RESERVED_67,
	IAPM_CFE_RESERVED_68,
	IAPM_CFE_RESERVED_69,
	IAPM_CFE_RESERVED_6A,
	IAPM_CFE_RESERVED_6B,
	IAPM_CFE_RESERVED_6C,
	IAPM_CFE_RESERVED_6D,
	IAPM_CFE_RESERVED_6E,
	IAPM_CFE_RESERVED_6F,
	IAPM_CFE_RESERVED_70,
	IAPM_CFE_RESERVED_71,
	IAPM_CFE_RESERVED_72,
	IAPM_CFE_RESERVED_73,
	IAPM_CFE_RESERVED_74,
	IAPM_CFE_RESERVED_75,
	IAPM_CFE_RESERVED_76,
	IAPM_CFE_RESERVED_77,
	IAPM_CFE_RESERVED_78,
	IAPM_CFE_RESERVED_79,
	IAPM_CFE_RESERVED_7A,
	IAPM_CFE_RESERVED_7B,
	IAPM_CFE_RESERVED_7C,
	IAPM_CFE_RESERVED_7D,
	IAPM_CFE_RESERVED_7E,
	IAPM_CFE_RESERVED_7F,
	IAPM_CFE_RESERVED_80,
	IAPM_CFE_RESERVED_81,
	IAPM_CFE_RESERVED_82,
	IAPM_CFE_RESERVED_83,
	IAPM_CFE_RESERVED_84,
	IAPM_CFE_RESERVED_85,
	IAPM_CFE_RESERVED_86,
	IAPM_CFE_RESERVED_87,
	IAPM_CFE_RESERVED_88,
	IAPM_CFE_RESERVED_89,
	IAPM_CFE_RESERVED_8A,
	IAPM_CFE_RESERVED_8B,
	IAPM_CFE_RESERVED_8C,
	IAPM_CFE_RESERVED_8D,
	IAPM_CFE_RESERVED_8E,
	IAPM_CFE_FREE_RUN_LINE_LENGTH_1_8F,
	IAPM_CFE_VBI_INFO_90,
	IAPM_CFE_WSS_1_91,
	IAPM_CFE_WSS_2_92,
	IAPM_CFE_EDTV_1_93,
	IAPM_CFE_EDTV_2_94,
	IAPM_CFE_EDTV_3_95,
	IAPM_CFE_CGMS_1_96,
	IAPM_CFE_CGMS_2_97,
	IAPM_CFE_CGMS_3_98,
	IAPM_CFE_CCAP_1_99,
	IAPM_CFE_CCAP_2_9A,
	IAPM_CFE_LETTERBOX_1_9B,
	IAPM_CFE_LETTERBOX_2_9C,
	IAPM_CFE_LETTERBOX_3_9D,
	IAPM_CFE_RESERVED_9E,
	IAPM_CFE_RESERVED_9F,
	IAPM_CFE_RESERVED_A0,
	IAPM_CFE_RESERVED_A1,
	IAPM_CFE_RESERVED_A2,
	IAPM_CFE_RESERVED_A3,
	IAPM_CFE_RESERVED_A4,
	IAPM_CFE_RESERVED_A5,
	IAPM_CFE_RESERVED_A6,
	IAPM_CFE_RESERVED_A7,
	IAPM_CFE_RESERVED_A8,
	IAPM_CFE_RESERVED_A9,
	IAPM_CFE_RESERVED_AA,
	IAPM_CFE_RESERVED_AB,
	IAPM_CFE_RESERVED_AC,
	IAPM_CFE_RESERVED_AD,
	IAPM_CFE_RESERVED_AE,
	IAPM_CFE_RESERVED_AF,
	IAPM_CFE_RESERVED_B0,
	IAPM_CFE_RESERVED_B1,
	IAPM_CFE_CRC_ENABLE_B2,
	IAPM_CFE_RESERVED_B3,
	IAPM_CFE_RESERVED_B4,
	IAPM_CFE_RESERVED_B5,
	IAPM_CFE_RESERVED_B6,
	IAPM_CFE_RESERVED_B7,
	IAPM_CFE_RESERVED_B8,
	IAPM_CFE_RESERVED_B9,
	IAPM_CFE_RESERVED_BA,
	IAPM_CFE_RESERVED_BB,
	IAPM_CFE_RESERVED_BC,
	IAPM_CFE_RESERVED_BD,
	IAPM_CFE_RESERVED_BE,
	IAPM_CFE_RESERVED_BF,
	IAPM_CFE_RESERVED_C0,
	IAPM_CFE_RESERVED_C1,
	IAPM_CFE_RESERVED_C2,
	IAPM_CFE_ADC_SWITCH_1_C3,
	IAPM_CFE_ADC_SWITCH_2_C4,
	IAPM_CFE_RESERVED_C5,
	IAPM_CFE_RESERVED_C6,
	IAPM_CFE_RESERVED_C7,
	IAPM_CFE_RESERVED_C8,
	IAPM_CFE_RESERVED_C9,
	IAPM_CFE_RESERVED_CA,
	IAPM_CFE_RESERVED_CB,
	IAPM_CFE_RESERVED_CC,
	IAPM_CFE_RESERVED_CD,
	IAPM_CFE_RESERVED_CE,
	IAPM_CFE_RESERVED_CF,
	IAPM_CFE_RESERVED_D0,
	IAPM_CFE_RESERVED_D1,
	IAPM_CFE_RESERVED_D2,
	IAPM_CFE_RESERVED_D3,
	IAPM_CFE_RESERVED_D4,
	IAPM_CFE_RESERVED_D5,
	IAPM_CFE_RESERVED_D6,
	IAPM_CFE_RESERVED_D7,
	IAPM_CFE_RESERVED_D8,
	IAPM_CFE_RESERVED_D9,
	IAPM_CFE_RESERVED_DA,
	IAPM_CFE_RESERVED_DB,
	IAPM_CFE_LETTERBOX_CTRL_1_DC,
	IAPM_CFE_LETTERBOX_CTRL_2_DD,
	IAPM_CFE_RESERVED_DE,
	IAPM_CFE_RESERVED_DF,
	IAPM_CFE_RESERVED_E0,
	IAPM_CFE_SD_OFFSET_CB_E1,
	IAPM_CFE_SD_OFFSET_CR_E2,
	IAPM_CFE_SD_SATURATION_CB_E3,
	IAPM_CFE_SD_SATURATION_CR_E4,
	IAPM_CFE_NTSC_V_BIT_BEGIN_E5,
	IAPM_CFE_NTSC_V_BIT_END_E6,
	IAPM_CFE_NTSC_F_BIT_TOGGLE_E7,
	IAPM_CFE_PAL_V_BIT_BEGIN_E8,
	IAPM_CFE_PAL_V_BIT_END_E9,
	IAPM_CFE_PAL_F_BIT_TOGGLE_EA,
	IAPM_CFE_RESERVED_EB,
	IAPM_CFE_RESERVED_EC,
	IAPM_CFE_RESERVED_ED,
	IAPM_CFE_RESERVED_EE,
	IAPM_CFE_RESERVED_EF,
	IAPM_CFE_RESERVED_F0,
	IAPM_CFE_RESERVED_F1,
	IAPM_CFE_RESERVED_F2,
	IAPM_CFE_RESERVED_F3,
	IAPM_CFE_DRIVE_STRENGTH_F4,
	IAPM_CFE_RESERVED_F5,
	IAPM_CFE_RESERVED_F6,
	IAPM_CFE_RESERVED_F7,
	IAPM_CFE_IF_COMP_CTRL_F8,
	IAPM_CFE_VS_MODE_CTRL_F9,

	BFIAPMCount,								// Number of indirect address/port registers.

	IAPM_ListEnd

} IAPMId;


#endif
